### ISSUE TITLE
xworkspaces is empty with pinned workspaces

### ISSUE THREAD

**Issue by dslaw** [jaagr/polybar#1097] opened 2018-03-15 06:02 UTC
With herbstluftwm, the xworkspaces area of the bar doesn't display anything and cannot be interacted with (scroll/click warns of no matching input area) when `pin-workspaces` is true. Log messages indicate that the ewmh module is active (start/rebuild cache). When it's false, everything works as expected.

Using polybar 3.1.0 and herbstluftwm 0.7.0.

Apologies if this just hasn't been added in yet - I know xworkspaces is still wip.

**Comment by NBonaparte** [comment] 2018-03-15 06:40
It should be working because hlwm implements `_NET_DESKTOP_VIEWPORT`... 

What is the output of `xprop -root _NET_DESKTOP_VIEWPORT`?

**Comment by dslaw** [comment] 2018-03-16 01:46
```
>>> xprop -root | grep "NET_DESKTOP_VIEWPORT"
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 1021507328
```
```
>>> polybar -m
eDP-1: 1600x900+0+0
```

The second value (coordinate?) of `_NET_DESKTOP_VIEWPORT` changes across restarts, but it's always some ridiculously large number.

**Comment by NBonaparte** [comment] 2018-03-16 01:49
That's interesting, the second coordinate is supposed to be the y coordinate of the desktop. This might be a bug with hlwm.

**Comment by patrick96** [comment] 2018-03-18 13:52
Might be some weird overflow issue. hlwm sets that property in https://github.com/herbstluftwm/herbstluftwm/blob/master/src/ewmh.cpp#L124:
```cpp
int buf[] = { 0, 0 };
XChangeProperty(g_display, g_root, g_netatom[NetDesktopViewport], XA_CARDINAL, 32, PropModeReplace, (unsigned char *) buf, LENGTH(buf));
```

However, I don't see anything immediately wrong with this.

**Comment by lyze237** [comment] 2018-04-11 11:56
I have the same problem.

```
$ xprop -root _NET_DESKTOP_VIEWPORT
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 2415376896
```

Maybe you could add a config option to display a list of workspaces?

**Comment by t-wissmann** [comment] 2018-04-11 12:37
Yes, it's an overflow issue. Even though 32 is passed to XChangeProperty, the buf array needs to be of type 'long int'.

**Comment by patrick96** [comment] 2018-04-14 15:29
Thanks for the quick fix @t-wissmann!

I can confirm that `xprop -root _NET_DESKTOP_VIEWPORT` now returns `0, 0`. As for polybar's behaviour, it will now display all workspaces if the bar is on the monitor with `(0, 0)` as its top-left coordinates, the others will still be empty. The `pin-workspaces` option in the `xworkspaces` module isn't really that useful as it just just distributes the defined desktops onto all viewports defined in `_NET_DESKTOP_VIEWPORT`. A workspace-monitor mapping isn't something that is defined in the EWMH spec as far as I can tell. This notion of a workspace being assigned to a monitor is something that doesn't exist inside hlwm.

I will open a PR to deprecate `pin-workspaces` in the `xworkspaces` module, it really only adds confusion, as the behaviour can be quite weird.

**Closed by patrick96** 2018-04-14 15:29 UTC
