### ISSUE TITLE
Cosmetic: tray pushes bar to the left, unaligning centered module

### ISSUE THREAD

**Issue by edgard** [jaagr/polybar#218] opened 2016-12-04 03:13 UTC
It's a small cosmetic issue, but whenever you have a tray, the bar center is actually calculated disregarding the tray size, therefore the center module is unaligned with the rest of the desktop.

Check this out, the terminal window is centered, but you can see the title on the middle is pushed to the left because of the tray.

https://u.teknik.io/H1Eaq.png

**Comment by jaagr** [comment] 2016-12-04 03:53
This is the intended behavior. If you don't want the tray to affect the bar window, use `tray-detached = true`

**Comment by edgard** [comment] 2016-12-04 04:04
Just tested, still pushed the bar with it.

What I am trying to do is that the right modules to be pushed to the left to accommodate changes but the center one stays centered to the total bar+tray length.

**Comment by jaagr** [comment] 2017-01-09 21:25
Closing this for as it won't be fixed for the current implementation. I've started on writing a systray module that will move the tray handling to a dedicated module.

**Closed by jaagr** 2017-01-09 21:25 UTC
