### ISSUE TITLE
Font `size` ineffective for NotoEmoji

### ISSUE THREAD

**Issue by FliiFe** [jaagr/polybar#1248] opened 2018-05-19 20:12 UTC
Whatever I do and no matter the font order, NotoEmoji is always rendered in huge font (huge as in close to 10 times the bar's height), and none of `size` and `pixelsize` change the font size.

It works fine for other fonts.
The vertical offset does work.

**Comment by patrick96** [comment] 2018-05-19 21:28
Duplicate of #905 

I wasn't able to fix it for myself, others seem to have managed though

**Closed by patrick96** 2018-05-19 21:28 UTC
Labels: duplicate
