### ISSUE TITLE
KeyError: 'Event struct'

### ISSUE THREAD

**Issue by dankehidayat** [jaagr/polybar#1233] opened 2018-05-13 14:40 UTC
The previous problem is now fixed #1228 . But now the error it's happening again after i try command `sudo make install`. Here's the output:
``` 
[  1%] Linking CXX static library libxpp.a
Traceback (most recent call last):
  File "/home/nishimiya/polybar/lib/xpp/generators/cpp_client.py", line 3163, in <module>
    from xcbgen.state import Module
  File "/usr/lib/python2.7/dist-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "/usr/lib/python2.7/dist-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "/usr/lib/python2.7/dist-packages/xcbgen/xtypes.py", line 1221, in <module>
    class EventStruct(Union):
  File "/usr/lib/python2.7/dist-packages/xcbgen/xtypes.py", line 1239, in EventStruct
    out = __main__.output['eventstruct']
KeyError: 'eventstruct'
lib/xpp/CMakeFiles/xpp.dir/build.make:68: recipe for target 'lib/xpp/libxpp.a' failed
make[2]: *** [lib/xpp/libxpp.a] Error 1
CMakeFiles/Makefile2:402: recipe for target 'lib/xpp/CMakeFiles/xpp.dir/all' failed
make[1]: *** [lib/xpp/CMakeFiles/xpp.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2```

**Comment by patrick96** [comment] 2018-05-13 20:10
Duplicate of #1090.
The fix is described in the [Wiki](https://github.com/jaagr/polybar/wiki/Known-Issues#keyerror-eventstruct)

**Closed by patrick96** 2018-05-13 20:10 UTC
Labels: build, duplicate
