### ISSUE TITLE
Memory usage (used memory)

### ISSUE THREAD

**Issue by torvic9** [jaagr/polybar#1141] opened 2018-04-03 08:33 UTC
Hello,
I noticed that the output of used memory doesn't correspond to anything in `free` or `/proc/meminfo`.
Since I don't speak C++, I don't know how the internal memory module calculates the used memory.
Can someone please explain this to me?
Alternatively I would just use a custom module with something like `free -h | awk 'FNR == 2 {print $3}'` but that's less than ideal...

**Comment by patrick96** [comment] 2018-04-03 08:40
Duplicate of #1137 

Polybar calculates the used memory from `MemTotal - MemAvailable`

**Closed by patrick96** 2018-04-03 08:40 UTC
Labels: duplicate
