### ISSUE TITLE
Font Awesome unmatched characters

### ISSUE THREAD

**Issue by Styxsz** [jaagr/polybar#946] opened 2018-01-09 10:53 UTC
Hey, since Font Awesome updated from 4.7.x to 5.x a few days ago, polybar seems to be unable to load most icons from the font. 
Following the wiki I made sure that the correct font is being loaded by polybar.
This is part of the output when running `polybar -l info barname`:
`Loaded font "Font Awesome 5 Free:size=16" (name=Font Awesome 5 Free, offset=0, file=/usr/share/fonts/TTF/fa-regular-400.ttf)`

I also made sure that the unmatched characters are actually contained by the font using `gucharmap`.

The warnings I am getting:
`warn: Dropping unmatched character  (U+f121)`
`warn: Dropping unmatched character  (U+f120)`
`warn: Dropping unmatched character  (U+f268)`

And here relevant parts of my config:
`font-0 = xos4 Terminus:style=Bold:pixelsize=22;1`
`font-1 = Font Awesome 5 Free:size=16;0`

**Comment by patrick96** [comment] 2018-01-09 10:53
Duplicate of #924

**Closed by patrick96** 2018-01-09 10:53 UTC

**Comment by pshoultz** [comment] 2018-03-16 05:36
i'm getting the same error a couple of months later.  It loads the font fine but it says dropping unmatched character.  

Loaded font "Font Awesome 5 Free:size=16" (name=Font Awesome 5 Free, offset=0, file=/usr/share/fonts/TTF/fa-regular-400.ttf)

warn: Dropping unmatched character 🖫 (U+1f5ab)

the fix for #924 doesn't work and I'm wondering if anyone else has the same issue again.
