### ISSUE TITLE
Emoji displaying incorrect size

### ISSUE THREAD

**Issue by ant-i-c-s** [jaagr/polybar#905] opened 2017-12-15 16:24 UTC
Steps:
1. Add emoji as a font

```
font-7 = NotoEmoji:size=7;
```

2. use emoji character (here it's in a webpage title, but it works on anything)
![image](https://user-images.githubusercontent.com/3298461/34050745-d631a600-e1b3-11e7-8c97-ad57aa057f71.png)

It ignores any size specification.

I don't know if this has anything to do with colour emoji being only a recent addition to cairo?

**Comment by NBonaparte** [comment] 2017-12-16 06:19
Can confirm this occurs with Noto Emoji.

It seems that this is an issue with the font itself. I found a workaround [here](https://github.com/googlei18n/noto-emoji/issues/36#issuecomment-343655365) which works but changing the pixel size to the desired value is needed (7 based on your setting). You may also need to shift the glyphs up or down a little.

**Comment by notantonia** [comment] 2017-12-18 00:36
I've not been able to get either that workaround nor the one in the comment before it to work. I'm not sure it's the exact same problem though, because emoji are displaying in the correct size in the browser and in the terminal for me. I'll see if this problem happens with other fonts though.

**Comment by NBonaparte** [comment] 2017-12-18 00:55
It worked everywhere else for me as well before the workaround. I think I had to restart or log out and back in, and also run `fc-cache -f` for polybar to show it correctly.

I had the same issue with Twemoji, so it seems to be a colour emoji problem.

**Comment by klorax** [comment] 2018-03-13 12:42
Hi,
any new information/progress on this?
I did not get the workaround to fix it, it might be due to font configs that loads after it (51+). The font (Noto Color Emoji) works fine "everywhere" (i3bar, gucharmap, firefox: 😈 ...) so did not want to mess too much with the font configs.

Thanks!

**Comment by NBonaparte** [comment] 2018-03-14 01:08
Found another solution on reddit: https://www.reddit.com/r/archlinux/comments/81wyq2/giant_emoji_in_terminal/dv617z8/
See if that works?

**Comment by klorax** [comment] 2018-03-14 13:31
Yeah, tried that all ready, unfortunately not.

**Comment by munyari** [comment] 2018-03-22 23:42
Just restarted my computer, and after having this problem for months it's now fixed! I updated noto-fonts-emoji yesterday (20180102-1 -> 20180102-2), so if you're still experiencing this, try updating the font.

**Comment by rawkode** [comment] 2018-03-26 15:21
I'm running `20180102-2`, @munyari; unfortunately the problem still persists

**Comment by LeoTindall** [comment] 2018-06-16 15:16
This problem exists for me, both on Ubuntu 18.04 and on Manjaro (fresh install). Any progress?

**Comment by notantonia** [comment] 2018-06-17 22:43
I can confirm that the newer Noto Emoji font (not the blob version `noto-fonts-emoji-blob` in AUR) doesn't display at a massive size.

**Comment by jebrosen** [comment] 2018-06-18 01:03
@notantonia which Noto Emoji font package (and version) exactly is that? I believe the last time it was updated I still had the issue.

**Comment by notantonia** [comment] 2018-06-18 11:32
@jebrosen `extra/noto-fonts-emoji`, version `20180425-1` in arch linux repos. I had tried some of the workarounds above a while ago, but I've checked `/etc/fonts/conf.d` and `.config/fontconfig` and not found anything, so it should be fine but not guaranteed.

**Comment by patrick96** [comment] 2018-06-18 12:04
@notantonia I have that package installed and still experience this. Likely there is some config option somewhere or some other package that will fix this.

**Comment by ant-i-c-s** [comment] 2018-10-03 18:15
I have been able to reduce the size of the emoji by specifying "scale" instead of "size". e.g.

`font-7 = NotoEmoji:scale=10;`

It is inversely proportional (a smaller number means larger characters).

**Comment by patrick96** [comment] 2018-10-03 18:31
Amazing, this works for me as well :smiley:

**Comment by patrick96** [comment] 2018-10-03 18:40
I have added a note to the [Known Issues](https://github.com/jaagr/polybar/wiki/Known-Issues#huge-emojis) page. I think we can close this.

**Closed by patrick96** 2018-10-03 18:40 UTC
Labels: confirmed

**Comment by kiminohero** [comment] 2019-05-23 18:44
> I have been able to reduce the size of the emoji by specifying "scale" instead of "size". e.g.
> 
> `font-7 = NotoEmoji:scale=10;`
> 
> It is inversely proportional (a smaller number means larger characters).

Yeah this works

**Comment by pvonmoradi** [comment] 2021-01-20 18:52
@antistic Thanks. Flags still don't work though (shows the letter of country in cyan).

**Comment by patrick96** [comment] 2021-01-20 19:59
@pvonmoradi Compound symbols don't work in polybar in general, that's why flags don't work.
