### ISSUE TITLE
Setting the fg color in a ramp state affects the rest of the bar

### ISSUE THREAD

**Issue by memeplex** [jaagr/polybar#1299] opened 2018-06-27 04:59 UTC
For example:

```
[module/cpu]
type = internal/cpu
interval = 5
format = %{A3:term htop:}<ramp-coreload> <label>%{A}
label = %percentage:2:3%%
ramp-coreload-font = 2
ramp-coreload-0-foreground = ${colors.base0A}
ramp-coreload-0 = ▁
ramp-coreload-1 = ▂
ramp-coreload-2 = ▃
ramp-coreload-3 = ▄
ramp-coreload-4 = ▅
ramp-coreload-5 = ▆
```

When the state coreload-0 is reached everything after this module turns colors.base0A.

**Comment by NBonaparte** [comment] 2018-07-18 04:10
Can't seem to reproduce this, can you post your config?

**Comment by nathanchere** [comment] 2018-08-17 05:45
I have mine working by colouring it like this:

```
ramp-coreload-0 = %{F#999}▁%{F-}
ramp-coreload-1 = %{F#977}▂%{F-}
ramp-coreload-2 = %{F#955}▃%{F-}
ramp-coreload-3 = %{F#931}▄%{F-}
ramp-coreload-4 = %{F#900}▅%{F-}
ramp-coreload-5 = %{F#B00}▆%{F-}
ramp-coreload-6 = %{F#D00}▇%{F-}
ramp-coreload-7 = %{F#F00}█%{F-}
```

**Comment by patrick96** [comment] 2018-08-17 10:33
I'm going to close this because @memeplex failed to provide further information. Seeing how @nathanchere fixed this, I think this is the same underlying issue as #937, which is an issue at the core of how we handle color tags.

**Closed by patrick96** 2018-08-17 10:33 UTC
