### ISSUE TITLE
Error 2 while trying to execute cmake .. to install

### ISSUE THREAD

**Issue by Larspolo** [jaagr/polybar#812] opened 2017-10-21 21:03 UTC
This is the output I get when running `cmake ..` or `cmake -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" ..`

```-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is Clang 4.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type specified; using RelWithDebInfo
-- Using supported compiler Clang-4.0.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.14.8
-- Found Libiw: /usr/lib/x86_64-linux-gnu/libiw.so  
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.11.1
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.11.1
--  Build:
--    Type: RelWithDebInfo
--    CC: /usr/bin/clang  -O2 -g -DNDEBUG
--    CXX: /usr/bin/clang++  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors -O2 -g -DNDEBUG
--    LD: /usr/bin/ld  
--  Targets:
--    polybar-msg
--    testsuite
--  Module support:
--    alsa
--    curl
--    i3
--    mpd
--    network
--  X extensions:
--    xcb-randr
--    xcb-randr (monitor support)
--    xcb-render
--    xcb-damage
--    xcb-sync
--    xcb-composite
--    xcb-xkb
--    xcb-xrm
-- Font not found: fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.12
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.13", minimum required is "2.7") 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib/x86_64-linux-gnu/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib/x86_64-linux-gnu/libxcb-ewmh.so  
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib/x86_64-linux-gnu/libxcb-util.so  
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Searching for xcbgen with python2
-- Found xcbgen in /usr/lib/python2.7/dist-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- XCB[XKB]: Found component XKB
-- Found XCB_XKB: /usr/lib/x86_64-linux-gnu/libxcb-xkb.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so;/usr/lib/x86_64-linux-gnu/libxcb-xkb.so  
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto xproto.xml
-- Checking for module 'jsoncpp>=1.7.7'
--   
-- Could not find jsoncpp>=1.7.7 -- building static lib...
-- JsonCpp Version: 1.7.7
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.13", minimum required is "2.6") 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/polybar/build
➜  build git:(4e2e2a7) sudo make install
Scanning dependencies of target xpp
[  1%] Linking CXX static library libxpp.a
list: size, ['red', 'green', 'blue']
list: size, ['red', 'green', 'blue']
[  1%] Built target xpp
Scanning dependencies of target jsoncpp_lib_static
[  2%] Building CXX object lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o
[  3%] Building CXX object lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_value.cpp.o
[  4%] Building CXX object lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_writer.cpp.o
[  5%] Linking CXX static library libjsoncpp.a
[  5%] Built target jsoncpp_lib_static
Scanning dependencies of target i3ipc++
[  5%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
[  7%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc-util.cpp.o
[  8%] Linking CXX static library libi3ipc++.a
[  8%] Built target i3ipc++
Scanning dependencies of target polybar
[  9%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/alsa/control.cpp.o
[ 10%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/alsa/mixer.cpp.o
[ 11%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/mpd.cpp.o
[ 12%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/net.cpp.o
[ 14%] Building CXX object bin/CMakeFiles/polybar.dir/cairo/utils.cpp.o
[ 15%] Building CXX object bin/CMakeFiles/polybar.dir/components/bar.cpp.o
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3026:42: error: use of undeclared identifier
      'xcb_randr_get_monitors_reply'; did you mean 'xcb_randr_get_providers_reply'?
                               SIGNATURE(xcb_randr_get_monitors_reply),
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                         xcb_randr_get_providers_reply
/tmp/polybar/lib/xpp/include/xpp/generic/signature.hpp:5:36: note: expanded from macro 'SIGNATURE'
  xpp::generic::signature<decltype(NAME), NAME>
                                   ^
/usr/include/xcb/randr.h:3390:1: note: 'xcb_randr_get_providers_reply' declared here
xcb_randr_get_providers_reply (xcb_connection_t                  *c  /**< */,
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3026:42: error: use of undeclared identifier
      'xcb_randr_get_monitors_reply'; did you mean 'xcb_randr_get_providers_reply'?
                               SIGNATURE(xcb_randr_get_monitors_reply),
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                         xcb_randr_get_providers_reply
/tmp/polybar/lib/xpp/include/xpp/generic/signature.hpp:5:43: note: expanded from macro 'SIGNATURE'
  xpp::generic::signature<decltype(NAME), NAME>
                                          ^
/usr/include/xcb/randr.h:3390:1: note: 'xcb_randr_get_providers_reply' declared here
xcb_randr_get_providers_reply (xcb_connection_t                  *c  /**< */,
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3033:43: error: use of undeclared identifier
      'xcb_randr_get_monitors_reply'; did you mean 'xcb_randr_get_providers_reply'?
                                SIGNATURE(xcb_randr_get_monitors_reply),
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                          xcb_randr_get_providers_reply
/tmp/polybar/lib/xpp/include/xpp/generic/signature.hpp:5:36: note: expanded from macro 'SIGNATURE'
  xpp::generic::signature<decltype(NAME), NAME>
                                   ^
/usr/include/xcb/randr.h:3390:1: note: 'xcb_randr_get_providers_reply' declared here
xcb_randr_get_providers_reply (xcb_connection_t                  *c  /**< */,
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3033:43: error: use of undeclared identifier
      'xcb_randr_get_monitors_reply'; did you mean 'xcb_randr_get_providers_reply'?
                                SIGNATURE(xcb_randr_get_monitors_reply),
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                          xcb_randr_get_providers_reply
/tmp/polybar/lib/xpp/include/xpp/generic/signature.hpp:5:43: note: expanded from macro 'SIGNATURE'
  xpp::generic::signature<decltype(NAME), NAME>
                                          ^
/usr/include/xcb/randr.h:3390:1: note: 'xcb_randr_get_providers_reply' declared here
xcb_randr_get_providers_reply (xcb_connection_t                  *c  /**< */,
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3044:24: error: use of undeclared identifier
      'xcb_randr_get_monitors_reply_t'; did you mean 'xcb_randr_get_providers_reply'?
                       xcb_randr_get_monitors_reply_t,
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       xcb_randr_get_providers_reply
/usr/include/xcb/randr.h:3390:1: note: 'xcb_randr_get_providers_reply' declared here
xcb_randr_get_providers_reply (xcb_connection_t                  *c  /**< */,
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3046:47: error: use of undeclared identifier
      'xcb_randr_monitor_info_t'; did you mean 'xcb_randr_mode_info_end'?
                                              xcb_randr_monitor_info_t,
                                              ^~~~~~~~~~~~~~~~~~~~~~~~
                                              xcb_randr_mode_info_end
/usr/include/xcb/randr.h:2022:1: note: 'xcb_randr_mode_info_end' declared here
xcb_randr_mode_info_end (xcb_randr_mode_info_iterator_t i  /**< */);
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3047:57: error: use of undeclared identifier
      'xcb_randr_monitor_info_next'; did you mean 'xcb_randr_mode_info_next'?
                                              SIGNATURE(xcb_randr_monitor_info_next),
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                        xcb_randr_mode_info_next
/tmp/polybar/lib/xpp/include/xpp/generic/signature.hpp:5:36: note: expanded from macro 'SIGNATURE'
  xpp::generic::signature<decltype(NAME), NAME>
                                   ^
/usr/include/xcb/randr.h:2010:1: note: 'xcb_randr_mode_info_next' declared here
xcb_randr_mode_info_next (xcb_randr_mode_info_iterator_t *i  /**< */);
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3047:57: error: use of undeclared identifier
      'xcb_randr_monitor_info_next'; did you mean 'xcb_randr_mode_info_next'?
                                              SIGNATURE(xcb_randr_monitor_info_next),
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                        xcb_randr_mode_info_next
/tmp/polybar/lib/xpp/include/xpp/generic/signature.hpp:5:43: note: expanded from macro 'SIGNATURE'
  xpp::generic::signature<decltype(NAME), NAME>
                                          ^
/usr/include/xcb/randr.h:2010:1: note: 'xcb_randr_mode_info_next' declared here
xcb_randr_mode_info_next (xcb_randr_mode_info_iterator_t *i  /**< */);
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3048:57: error: use of undeclared identifier
      'xcb_randr_monitor_info_sizeof'; did you mean 'xcb_randr_get_crtc_info_sizeof'?
                                              SIGNATURE(xcb_randr_monitor_info_sizeof),
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                        xcb_randr_get_crtc_info_sizeof
/tmp/polybar/lib/xpp/include/xpp/generic/signature.hpp:5:36: note: expanded from macro 'SIGNATURE'
  xpp::generic::signature<decltype(NAME), NAME>
                                   ^
/usr/include/xcb/randr.h:2638:1: note: 'xcb_randr_get_crtc_info_sizeof' declared here
xcb_randr_get_crtc_info_sizeof (const void  *_buffer  /**< */);
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3048:57: error: use of undeclared identifier
      'xcb_randr_monitor_info_sizeof'; did you mean 'xcb_randr_get_crtc_info_sizeof'?
                                              SIGNATURE(xcb_randr_monitor_info_sizeof),
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                        xcb_randr_get_crtc_info_sizeof
/tmp/polybar/lib/xpp/include/xpp/generic/signature.hpp:5:43: note: expanded from macro 'SIGNATURE'
  xpp::generic::signature<decltype(NAME), NAME>
                                          ^
/usr/include/xcb/randr.h:2638:1: note: 'xcb_randr_get_crtc_info_sizeof' declared here
xcb_randr_get_crtc_info_sizeof (const void  *_buffer  /**< */);
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3049:57: error: use of undeclared identifier
      'xcb_randr_get_monitors_monitors_iterator'
                                              SIGNATURE(xcb_randr_get_monitors_monitors_iterator)>
                                                        ^
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3049:98: error: expected a type
                                              SIGNATURE(xcb_randr_get_monitors_monitors_iterator)>
                                                                                                 ^
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3050:23: error: expected a type
                      >
                      ^
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3054:33: error: use of undeclared identifier
      'xcb_randr_get_monitors_reply_t'; did you mean 'xcb_randr_get_providers_reply'?
                                xcb_randr_get_monitors_reply_t,
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                xcb_randr_get_providers_reply
/usr/include/xcb/randr.h:3390:1: note: 'xcb_randr_get_providers_reply' declared here
xcb_randr_get_providers_reply (xcb_connection_t                  *c  /**< */,
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3056:56: error: use of undeclared identifier
      'xcb_randr_monitor_info_t'; did you mean 'xcb_randr_mode_info_end'?
                                                       xcb_randr_monitor_info_t,
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
                                                       xcb_randr_mode_info_end
/usr/include/xcb/randr.h:2022:1: note: 'xcb_randr_mode_info_end' declared here
xcb_randr_mode_info_end (xcb_randr_mode_info_iterator_t i  /**< */);
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3057:66: error: use of undeclared identifier
      'xcb_randr_monitor_info_next'; did you mean 'xcb_randr_mode_info_next'?
                                                       SIGNATURE(xcb_randr_monitor_info_next),
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                 xcb_randr_mode_info_next
/tmp/polybar/lib/xpp/include/xpp/generic/signature.hpp:5:36: note: expanded from macro 'SIGNATURE'
  xpp::generic::signature<decltype(NAME), NAME>
                                   ^
/usr/include/xcb/randr.h:2010:1: note: 'xcb_randr_mode_info_next' declared here
xcb_randr_mode_info_next (xcb_randr_mode_info_iterator_t *i  /**< */);
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3057:66: error: use of undeclared identifier
      'xcb_randr_monitor_info_next'; did you mean 'xcb_randr_mode_info_next'?
                                                       SIGNATURE(xcb_randr_monitor_info_next),
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                 xcb_randr_mode_info_next
/tmp/polybar/lib/xpp/include/xpp/generic/signature.hpp:5:43: note: expanded from macro 'SIGNATURE'
  xpp::generic::signature<decltype(NAME), NAME>
                                          ^
/usr/include/xcb/randr.h:2010:1: note: 'xcb_randr_mode_info_next' declared here
xcb_randr_mode_info_next (xcb_randr_mode_info_iterator_t *i  /**< */);
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3058:66: error: use of undeclared identifier
      'xcb_randr_monitor_info_sizeof'; did you mean 'xcb_randr_get_crtc_info_sizeof'?
                                                       SIGNATURE(xcb_randr_monitor_info_sizeof),
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                 xcb_randr_get_crtc_info_sizeof
/tmp/polybar/lib/xpp/include/xpp/generic/signature.hpp:5:36: note: expanded from macro 'SIGNATURE'
  xpp::generic::signature<decltype(NAME), NAME>
                                   ^
/usr/include/xcb/randr.h:2638:1: note: 'xcb_randr_get_crtc_info_sizeof' declared here
xcb_randr_get_crtc_info_sizeof (const void  *_buffer  /**< */);
^
In file included from /tmp/polybar/src/components/bar.cpp:4:
In file included from /tmp/polybar/include/components/config.hpp:13:
In file included from /tmp/polybar/include/x11/xresources.hpp:14:
In file included from /tmp/polybar/include/x11/connection.hpp:10:
In file included from /tmp/polybar/include/components/screen.hpp:7:
In file included from /tmp/polybar/include/x11/extensions/randr.hpp:10:
/tmp/polybar/lib/xpp/include/xpp/proto/randr.hpp:3058:66: error: use of undeclared identifier
      'xcb_randr_monitor_info_sizeof'; did you mean 'xcb_randr_get_crtc_info_sizeof'?
                                                       SIGNATURE(xcb_randr_monitor_info_sizeof),
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                 xcb_randr_get_crtc_info_sizeof
/tmp/polybar/lib/xpp/include/xpp/generic/signature.hpp:5:43: note: expanded from macro 'SIGNATURE'
  xpp::generic::signature<decltype(NAME), NAME>
                                          ^
/usr/include/xcb/randr.h:2638:1: note: 'xcb_randr_get_crtc_info_sizeof' declared here
xcb_randr_get_crtc_info_sizeof (const void  *_buffer  /**< */);
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
bin/CMakeFiles/polybar.dir/build.make:182: recipe for target 'bin/CMakeFiles/polybar.dir/components/bar.cpp.o' failed
make[2]: *** [bin/CMakeFiles/polybar.dir/components/bar.cpp.o] Error 1
CMakeFiles/Makefile2:798: recipe for target 'bin/CMakeFiles/polybar.dir/all' failed
make[1]: *** [bin/CMakeFiles/polybar.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by patrick96** [comment] 2017-10-21 21:10
Duplicate of #644, please see the [Wiki](https://github.com/jaagr/polybar/wiki/Compiling#version-mismatch-between-xcb-proto-and-libxcb-randr0-dev) for instructions on how to resolve this.

**Closed by patrick96** 2017-10-21 21:10 UTC
Labels: build, duplicate
