### ISSUE TITLE
Can't get workspace icons to work on i3

### ISSUE THREAD

**Issue by Jyugo-GH** [jaagr/polybar#1577] opened 2019-01-03 15:18 UTC
## Workspace icons are not displaying
*Hello, I have the problem that the icons I have set for the i3 workspaces are not showing in polybar*

The bar only shows "1" "2" "3" and so on.

![deepinscreenshot_select-area_20190103090912](https://user-images.githubusercontent.com/37481128/50644875-df51ef80-0f50-11e9-8bcb-6375d8463069.png)

I have set in my i3 config the following code:

```# Workspace names
# to display names or symbols instead of plain workspace numbers you can use
# something like: set $ws1 1:mail
#                 set $ws2 2:
set $ws1 1:
set $ws2 2:
set $ws3 3:
set $ws4 4:
set $ws5 5:🗏
set $ws6 6:❻
set $ws7 7:❼
set $ws8 8:❽
```

And in my polybar config this:

```[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

ws-icon-1 = 1:
ws-icon-2 = 2:
ws-icon-3 = 3:
ws-icon-4 = 4:
ws-icon-5 = 5:🗏
ws-icon-6 = 6:❻
ws-icon-7 = 7:❼
ws-icon-8 = 8:❽

; Only show workspaces on the same output as the bar
;pin-workspaces = true

label-active-font = 3

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-background = ${module/bspwm.label-focused-background}
label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = ${module/bspwm.label-focused-padding}
label-focused-font = 3

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = ${module/bspwm.label-occupied-padding}
label-unfocused-font = 3

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}
label-visible-font = 3

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${module/bspwm.label-urgent-background}
label-urgent-padding = ${module/bspwm.label-urgent-padding}
label-urgent-font = 3

; Separator in between workspaces
; label-separator = |
```
(By the way, font 3 is Noto Sans.)

If I delete the "XNUMBER:" part, so as to only have the icon:

`set $ws1 `
`ws-icon-1 = `

Polybar displays "-1" in every workspace

![deepinscreenshot_select-area_20190103091037](https://user-images.githubusercontent.com/37481128/50644898-f1339280-0f50-11e9-91ff-13ebd5b7bfb7.png)

## Environment:
* WM: i3-gaps
* Output of `polybar -vvv`: 

```polybar

 3.3.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/sbin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now```

**Comment by patrick96** [comment] 2019-01-03 17:46
Duplicate of #1569

**Closed by patrick96** 2019-01-03 17:46 UTC
