### ISSUE TITLE
Battery Percentage refresh issue

### ISSUE THREAD

**Issue by Kakashiiiiy** [jaagr/polybar#1391] opened 2018-08-20 11:52 UTC
I am using the battery module, with xf86-video-intel everything works fine.
But now I am using the modsetting driver.

Now the screen has 5% brightness but polybar displays 10% (The module displays the backlight +/- 5% and somethimes correctly). So I decided to write a Custom script.

`#! /bin/bash`
`max=$(cat /sys/class/backlight/intel_backlight/max_brightness)`
`actual=$(cat /sys/class/backlight/intel_backlight/brightness)`
`echo "$actual / $max * 100"| bc -l | sed 's/[.].*$//'`

After I execute it to see if evertything works properly polybar updates the internal battery and displays the correct percentage.

I guess its a bug because polybar updates the battery module just after I execute 
`cat /sys/class/backlight/intel_backlight/brightness`
Or maybe the file is the problem.

**Comment by patrick96** [comment] 2018-08-20 12:26
Duplicate of #1180

**Closed by patrick96** 2018-08-20 12:26 UTC
