### ISSUE TITLE
Problem building with jsoncpp-1.7.7 on Fedora 25

### ISSUE THREAD

**Issue by dikeert** [jaagr/polybar#818] opened 2017-10-27 11:39 UTC
I receive this error:

```
Building CXX object lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o
/home/aner/Downloads/GitHub/polybar/lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/json_reader.cpp: In member function ‘bool Json::OurReader::readToken(Json::OurReader::Token&)’:
/home/aner/Downloads/GitHub/polybar/lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/json_reader.cpp:1230:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
     if (features_.allowSingleQuotes_) {
     ^~
/home/aner/Downloads/GitHub/polybar/lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/json_reader.cpp:1235:3: note: here
   case '/':
   ^~~~
cc1plus: all warnings being treated as errors
make[2]: *** [lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/build.make:63: lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:542: lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by patrick96** [comment] 2017-10-27 14:09
Duplicate of #753

**Closed by patrick96** 2017-10-27 14:09 UTC
Labels: duplicate
