### ISSUE TITLE
Cryptic error while building polybar

### ISSUE THREAD

**Issue by siddharthist** [jaagr/polybar#320] opened 2017-01-11 18:37 UTC
Hi, I'm trying to package polybar for NixOS Linux, and I'm getting the following error during the build phase:
```
-- Build files have been written to: /tmp/nix-build-basket-2.4.8.drv-0/polybar-66131c8/build
building
make flags: SHELL=/nix/store/hgbbz9kv3m7583rmb339595xrvaiw8bg-bash-4.4-p5/bin/bash    
Scanning dependencies of target xpp
[  1%] Linking CXX static library libxpp.a
[  1%] Built target xpp
Scanning dependencies of target polybar
[  2%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/alsa/control.cpp.o
<command-line>:0:1: error: macro names must be identifiers
<command-line>:0:1: error: macro names must be identifiers
<command-line>:0:1: error: macro names must be identifiers
<command-line>:0:1: error: macro names must be identifiers
<command-line>:0:1: error: macro names must be identifiers
<command-line>:0:1: error: macro names must be identifiers
<command-line>:0:1: error: macro names must be identifiers
make[2]: *** [bin/CMakeFiles/polybar.dir/build.make:63: bin/CMakeFiles/polybar.dir/adapters/alsa/control.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:330: bin/CMakeFiles/polybar.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
builder for ‘/nix/store/9ik26yb8l8rvyrv1k9d2ff5kav0vfvls-basket-2.4.8.drv’ failed with exit code 2
error: build of ‘/nix/store/9ik26yb8l8rvyrv1k9d2ff5kav0vfvls-basket-2.4.8.drv’ failed
```
I'm not experienced with CMake builds, and was hoping you might be able to help me understand what's going on.

**Comment by mrkgnao** [comment] 2017-01-12 07:44
It seems I'm in the same position: check https://github.com/jaagr/polybar/issues/308.

**Comment by jaagr** [comment] 2017-01-12 14:39
Hi, can you post the initial configure output from running `cmake ..`

**Comment by jaagr** [comment] 2017-01-13 00:21
Closing as duplicate of #308

**Closed by jaagr** 2017-01-13 00:21 UTC

**Comment by siddharthist** [comment] 2017-01-13 21:06
Thanks for pointing me in the right direction, you two! Sorry for the duplicate issue!
