### ISSUE TITLE
Failed to execute default web browser

### ISSUE THREAD

**Issue by Dobbie03** [jaagr/polybar#1482] opened 2018-10-21 21:49 UTC
Okay I am running Polybar on Arch.  I am using a custom mail module

```
[module/mail]
type = custom/script
interval = 30
format = <label>
format-prefix = ""
label-padding = 1
exec = $HOME/.config/polybar/mail
click-left = exo-open --launch WebBrowser https://mail.google.com/mail/u/0/#inbox &
click-right = exo-open --launch WebBrowser https://mail.protonmail.com/login &
format-padding = 5
```

This is the script:

```
#!/usr/bin/python

import imaplib
obj = imaplib.IMAP4_SSL('imap.gmail.com',993)
obj.login('gmail user','password') # write your email and password
obj.select()
print(len(obj.search(None, 'UnSeen')[1][0].split()))
```
Qutebrowser is my default browser and is set in exo-preferred as default also.  When clicking either left or right the browser opens to the correct page, either Gmail or Protonmail but I get an error prompt.

![image](https://user-images.githubusercontent.com/14961904/47272850-c25f7e80-d5e7-11e8-9311-136f5bde5cc0.png)

This only happens with Qutebrowser not Firefox so I'm not 100% this is even a Polybar issue.

**Comment by patrick96** [comment] 2018-10-21 21:51
Hmm. But executing `exo-open --launch WebBrowser https://mail.google.com/mail/u/0/#inbox` and the other one in the terminal works fine with both browsers?

Can you try to replace those two lines with the following ones and report back if that fixes it:
```dosini
click-left = exo-open --launch WebBrowser https://mail.google.com/mail/u/0/#inbox >/dev/null 2>&1 &
click-right = exo-open --launch WebBrowser https://mail.protonmail.com/login >/dev/null 2>&1 &
```

**Comment by Dobbie03** [comment] 2018-10-21 21:54
> But executing exo-open --launch WebBrowser https://mail.google.com/mail/u/0/#inbox and the other one in the terminal works fine with both browsers?

Changing to your suggestion fixed the issue.  Thanks for the tip.

**Comment by patrick96** [comment] 2018-10-21 22:07
Seems like you are suffering from the same bug as [this](https://github.com/jaagr/polybar/wiki/Known-Issues#click-commands-are-not-executed), reported in #916. Gonna mark this as a duplicate
Has been on my TODO list for the longest time, just need to find some free time to fix it.

**Comment by patrick96** [comment] 2018-10-21 22:07
Duplicate of #916

**Closed by patrick96** 2018-10-21 22:07 UTC
