### ISSUE TITLE
Volume stuck after changing output device

### ISSUE THREAD

**Issue by wedens** [jaagr/polybar#472] opened 2017-03-05 16:15 UTC
After I change output device in pulseaudio, volume indicator is stuck. No errors in console.
e.g. I change output "external sound card" to "headphones" and then back to "external sound card" and indicator stops displaying actual volume (and it always displays the same number).

**Comment by zestyr** [comment] 2017-03-07 15:13
I experience this as well.

Another problem is if you set different left/right volumes in pavumixer, and use polybar's volume module to change volume, it'll reset left/right to be the same.

**Comment by hschreck** [comment] 2017-04-01 18:14
I think the left-right issue is fairly common.  Is there a way to lock PA to handle it as expected?

**Comment by jaagr** [comment] 2017-04-02 15:40
The reason it doesn't change after you've switched output device is because the mixers and channels are setup on launch and there are currently no handling that listens for changes of them. It can probably be added but I would need to look in to it more.

The left/right channel volume can also be fixed so that polybar adjusts the volume relative to each channel. Had no use for it when I wrote it so didn't think about it then.

**Comment by ecly** [comment] 2017-08-04 21:00
I think this would be a cool feature as well. Even if it was just attainable with a script or something of the sorts.

**Comment by CarlosMChica** [comment] 2017-09-10 18:24
+1

**Comment by NBonaparte** [comment] 2018-01-20 21:18
Closing because the Pulseaudio module provides a workaround to this issue.

**Closed by NBonaparte** 2018-01-20 21:18 UTC
Labels: bug

**Comment by CarlosMChica** [comment] 2018-01-21 12:21
@NBonaparte would you mind sharing what the workaround is?

**Comment by ecly** [comment] 2018-01-21 13:17
@CarlosMChica [here](https://github.com/ecly/dotfiles/blob/master/Scripts/pavolume.sh) is my slightly modified version that works nicely for two audio devices and includes mute/icons etc.

**Comment by NBonaparte** [comment] 2018-01-21 16:48
The [Pulseaudio module](https://github.com/jaagr/polybar/wiki/Module:-pulseaudio) uses Pulseaudio as a backend and not ALSA (see #779). Thus this issue does not apply anymore, because the module tracks if the sink changes.

**Comment by ecly** [comment] 2018-07-18 13:30
@NBonaparte I've only just now gotten around to trying the pulseaudio module, instead of my earlier mentioned script. 

When changing the default sink while polybar is running using `pacmd set-default-sink 1` the changes are not reflected by the pulseaudio module. I'm using an external soundcard and switching between onboard and the external one. I do not specify a sink in for the module configuration. The module is instead stuck showing the volume of the sink that was the default when polybar started. If I restart polybar after changing the sink, the changes are reflected.

Is this expected behavior of the module? I thought it would catch me changing the default sink - but couldn't find it stating so explicitly in the wiki.

I

**Comment by NBonaparte** [comment] 2018-07-18 16:36
This should have been fixed in #1168; are you using the latest commit from master?

**Comment by ecly** [comment] 2018-07-18 16:47
@NBonaparte ah - sorry about that. I didn't see that fix. I'm using `polybar-git` on Arch which is using a version from February, so that's the issue. Cheers!

**Comment by NBonaparte** [comment] 2018-07-18 19:01
You can just reinstall the package, it will automatically build it from master.

**Comment by ecly** [comment] 2018-07-18 19:03
@NBonaparte god damnit - I thought it was glued to some commit for some reason, despite the `-git` suffix. Cheers! It's working!
