### ISSUE TITLE
Breaking after an update

### ISSUE THREAD

**Issue by Doshirae** [jaagr/polybar#872] opened 2017-12-01 09:07 UTC
Hello
I'm on ArchLinux, and after I updated my packages this morning, Polybar broke because it couldn't find libjsoncpp.so.11
(the update seems to have deleted it in profit of libjsoncpp.so.19)
I'm aware that Arch has bleeding age updates of the packages, therefore all distros may not have that problem

But is that possible to add support for libjsoncpp.so.19 ? Or do you have to use only one ? (I really don't know i'm sorry if my question looks silly)

Anyway, thanks for that neat piece of software ♥

**Comment by patrick96** [comment] 2017-12-01 09:19
Looks like a duplicate of #871 
You will need to recompile polybar and maybe apply https://github.com/jaagr/i3ipcpp/pull/4 in the i3ipcpp submodule

**Closed** 2017-12-01 09:19 UTC
Labels: duplicate
