### ISSUE TITLE
wireless_tools considered deprecated

### ISSUE THREAD

**Issue by mindstormer12** [jaagr/polybar#300] opened 2017-01-04 02:51 UTC
wireless tools package considered deprecated, perhaps consider an alternative?

* https://en.wikipedia.org/wiki/Wireless_tools_for_Linux

* https://wiki.archlinux.org/index.php/Wireless_network_configuration#Manual_setup

**Comment by NBonaparte** [comment] 2017-01-04 03:18
Duplicate of #277.

**Closed** 2017-01-07 11:56 UTC
