### ISSUE TITLE
Foreground  color overflows when setting xbacklight to max

### ISSUE THREAD

**Issue by benjaminshafii** [jaagr/polybar#575] opened 2017-05-10 21:46 UTC
```
/bin/polybar --version
polybar 3.0.5-10-g5c41e3d

Features: +alsa +curl +i3 +mpd +network
```

![out](https://cloud.githubusercontent.com/assets/11430621/25922793/cb1ae536-35da-11e7-879f-f5a1660fc519.gif)

My config:
```
[module/xbacklight]
type = internal/xbacklight

format = <label> <bar>
label = BL

bar-width = 10
bar-indicator = |
bar-indicator-foreground = #ff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = ${colors.secondary}
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.secondary}
```

**Comment by jaagr** [comment] 2017-05-12 07:41
Could you post your full config?

**Comment by benjaminshafii** [comment] 2017-05-13 07:36
```
;=====================================================
;
;   To learn more about how to configure Polybar
;   go to https://github.com/jaagr/polybar
;
;   The README contains alot of information
;
;=====================================================
[colors]
background = #222
;background-alt = #444
foreground = #ebdbb2
;foreground-alt = #555
primary = #fabd2f
secondary = #e60053
alert = #bd2c40

[bar/top]
monitor = ${env:MONITOR}

width = 100% 
height = ${env:POLYBAR_HEIGHT}

locale = de_DE.UTF-8
background = ${colors.background}
foreground = ${colors.foreground}
dpi = ${env:DPI}

font-0 = Courrier New:weight = Regular:size=11;0
font-1 = FontAwesome:weight = bold :size=9;1

modules-left =  date
modules-center = i3
modules-right = volume xbacklight keyboard battery powermenu

tray-position = left
tray-padding = 15
tray-transparent = false
tray-detached = false
tray-maxsize = ${env:POLYBAR_TRAY_SIZE}
tray-background = ${colors.background}

underline-size = 3

spacing = 1
padding-left = 1
padding-right = 1
module-margin-left = 3
module-margin-right = 3

[module/keyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = "  "
format-prefix-foreground = ${colors.foreground}
format-prefix-underline = ${colors.secondary}

label-layout = %layout%
label-layout-underline = ${colors.secondary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/filesystem]
type = internal/fs

; Mountpoints to display
mount-0 = /


[module/battery]
type = internal/battery
battery = BAT0
adapter = AC0
full-at = 98

format-charging = <animation-charging> <label-charging>

format-discharging = <ramp-capacity> <label-discharging>

format-full-prefix = " "
;format-full-prefix-foreground = ${colors.foreground-alt}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-foreground = #999

animation-charging-0 =   
animation-charging-1 =   
animation-charging-2 =   
;animation-charging-foreground = ${colors.foreground-alt}
animation-charging-framerate = 750

[module/volume]
type = internal/volume

format-volume = <ramp-volume> <label-volume>
module-margin-right = 1
ramp-volume-0 =  
ramp-volume-1 =  
ramp-volume-2 = 

format-volume-background = ${colors.background}
format-volume-foreground = ${colors.foreground}

label-muted = 🔇muted


[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%
module-margin-left = 2
format-padding = 2
format-background = ${colors.background}

[module/i3]
type = internal/i3
pin-workspaces = true
wrapping-scroll = false
enable-click = true
format = <label-state>

label-focused = %index%
label-focused-underline = ${colors.secondary}
label-focused-padding = 2


[module/date]
type = internal/date
interval = 1
date = "  %H:%M"
date-alt = "  %A, %d %B"

;format = %date% 
;format-padding = 1
;format-background = #7aa04b
;

[module/xbacklight]
type = internal/xbacklight

format = <label> <bar>
label = " "

bar-width = 10
bar-indicator = |
bar-indicator-foreground = #ff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = ${colors.secondary}
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.secondary}

[module/powermenu]
type = custom/menu

label-open =   
label-open-foreground = ${colors.foreground}
label-open-background = ${colors.background}
label-close =  cancel
label-close-foreground = ${colors.foreground}
label-close-background = ${colors.background}
label-separator = |
label-separator-foreground = ${colors.foreground}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = shutdown
menu-0-1-exec = menu-open-2
menu-0-2 = logout
menu-0-2-exec = menu-open-3

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = systemctl reboot

menu-2-0 = shutdown
menu-2-0-exec = systemctl poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

menu-3-0 = logout
menu-3-0-exec = i3-msg exit
menu-3-1 = cancel
menu-3-1-exec = menu-open-0 vim:ft=dosini

[global/wm]
margin-top = 5
margin-bottom = 5
```

**Comment by jaagr** [comment] 2017-05-17 21:13
Could you update and see if 2e8cc7f fixes your issue

**Comment by benjaminshafii** [comment] 2017-05-20 17:34
I'm at `28431be` and the change is still persisting

**Comment by jaagr** [comment] 2017-05-21 11:11
I will try to reproduce the issue with your config.

**Comment by oquinena** [comment] 2017-05-21 20:38
I am also having this issue. Although in my case the overflowing color is coming from both the volume bar and backlight. Everything right of volumebar has the forecolor of current volume. Unless volume is muted, then the color of backlight is color.foreground.

This is current config:

```
; vim: filetype=dosini
;=====================================================
;
;   To learn more about how to configure Polybar
;   go to https://github.com/jaagr/polybar
;
;   The README contains alot of information
;
;=====================================================

[colors]
background = #2F343F
background-alt = #444
foreground = #dfdfdf
foreground-alt = #55
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

[global/wm]
;margin-top = 5
;margin-bottom = 5

[bar/daniels]
monitor = ${env:MONITOR:eDP1}
width = 100%
height = 40
offset-x = 0
offset-y = 0

;background = ${xrdb:color9}
background = ${colors.background}
foreground = ${colors.foreground}

overline-size = 2
overline-color = #f00
underline-size = 2
underline-color = #00f

border-bottom.size = 2
border-bottom-color = #333

spacing = 1
padding-left = 0
padding-right = 2
module-margin-left = 1
module-margin-right = 2

;font-0 = SFNS Display:62
font-0 = Terminus:pixelsize=22:fontformat=truetype;1
font-1 = unifont:size=18:heavy:fontformat=truetype;0
font-2 = '-*-tamsyn-medium-r-normal-*-12-*-*-*-*-*-*-1' -f '-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1' 
font-3 = FontAwesome:pixelsize=20;2

modules-left = bspwm i3 xwindow 
modules-center = 
modules-right = cpu vpncheck_hemma vpncheck_angkarr backlight volume xkeyboard memory wifi eth battery date powermenu

tray-position = right
tray-padding = 2
;tray-transparent = true
;tray-background = #0063ff

wm-restack = bspwm
;wm-restack = i3

;override-redirect = true

scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev


[module/xwindow]
type = internal/xwindow
label = %title:0:90:...%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-underline = ${colors.secondary}
format-prefix = " "
format-prefix-foreground = ${colors.foreground}

label-layout = %layout%

label-indicator-padding = 2
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /
mount-1 = /home/nomad
;mount-2 = /invalid/mountpoint

label-mounted = %mountpoint%: %percentage_free%

label-unmounted = %mountpoint%: not mounted
label-unmounted-foreground = ${colors.foreground-alt}

[module/bspwm]
type = internal/bspwm
ws-icon-default = x

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-occupied = %index%
label-occupied-padding = 2
;label-occupied-underline = ${colors.primary}

label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

label-focused = %name%
label-focused-background = ${module/bspwm.label-focused-background}
label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = ${module/bspwm.label-focused-padding}

label-unfocused = %name%
label-unfocused-padding = ${module/bspwm.label-occupied-padding}

label-urgent = %name%
label-urgent-background = ${module/bspwm.label-urgent-background}
label-urgent-padding = ${module/bspwm.label-urgent-padding}

label-visible = %name%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

[module/mpd]
type = internal/mpd

format-online = <label-song>  <icon-prev> <icon-seekb> <icon-stop> <toggle> <icon-seekf> <icon-next>  <icon-repeat> <icon-random>

label-song-maxlen = 25
label-song-ellipsis = true

icon-prev = 
icon-seekb = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 
icon-seekf = 

icon-random = 
icon-repeat = 

toggle-on-foreground = ${colors.primary}
toggle-off-foreground = #66

[module/backlight]
type = internal/xbacklight

format = <label> <bar>
label =  

bar-width = 10
bar-indicator = │
bar-indicator-foreground = #ff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground}
format-underline = #f90000
label = %percentage%%

[module/memory]
type = internal/memory
interval = 2
;format = <forprefix> <label>
format-prefix = " "
format-prefix-foreground = ${colors.foreground}
format-underline = #4bffdc
label = %percentage_used%%

[module/wifi]
type = custom/script
interval = 60
exec = "nmcli d show wlp6s0 | grep 'GENERAL.CONNECTION' | awk '{ print $2 }'"
format-prefix = " "
format-underline = #9f78e1
format-prefix-foreground = ${colors.foreground}

[module/wlan]
type = internal/network
interface = wlp6s0
interval = 3.0

format-connected = <label-connected>
format-connected-underline = #9f78e1
format-disconnected-underline = ${self.format-connected-underline}

label-connected = %essid%
label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${colors.foreground-alt}

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = ${colors.foreground-alt}

[module/eth]
type = internal/network
interface = enp0s20u6
interval = 3.0

format-connected-underline = #55aa55
format-connected-prefix = " "
format-connected-foreground-foreground = ${colors.foreground-alt}
label-connected = %local_ip%

format-disconnected-underline = ${self.format-connected-underline}
label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${colors.foreground-alt}

[module/date]
type = internal/date
interval = 5

date =
date-alt = " %Y-%m-%d"

time = %H:%M
time-alt = %H:%M:%S

format-prefix = 
format-prefix-foreground = #dfdfdf 
format-underline = #0a6cf5

label = %date% %time%

[module/volume]
type = internal/volume

format-volume = <label-volume> <bar-volume>
label-volume = "   "
label-volume-foreground = #dfdfdf

format-muted-prefix = " "
format-muted-foreground = #ffb52a
;format-muted-foreground = ${colors.foreground}
label-muted = "muted "

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = │
bar-volume-indicator-font = 2
bar-volume-indicator-foreground = #ff
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD
full-at = 100

format-charging = <animation-charging> <label-charging>
format-charging-underline = #ffb52a

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}

format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground}
format-full-underline = ${self.format-charging-underline}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${colors.foreground}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${colors.foreground}
animation-charging-framerate = 750

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-underline = #f50a4d
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature%
label-warn = %temperature%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground}

[module/powermenu]
type = custom/menu

label-open =  power
label-open-foreground = ${colors.foreground}
label-close =  cancel
label-close-foreground = ${colors.foreground}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 =  reboot
menu-0-0-exec = menu-open-1
menu-0-1 =  power off
menu-0-1-exec = menu-open-2

menu-1-0 =  cancel
menu-1-0-exec = menu-open-0
menu-1-1 =  reboot
menu-1-1-exec = sudo shutdown -r now 

menu-2-0 =  power off
menu-2-0-exec = sudo shutdown -h now
menu-2-1 =  cancel
menu-2-1-exec = menu-open-0

[module/vpncheck_jobb]
type = custom/script
exec = pgrep openconnect
interval = 5
label = ängkärr
format-underline = #268bd2
format-prefix = " "

[module/vpncheck_hemma]
type = custom/script
exec = pgrep pptp
interval = 5
label = hemma
format-underline = #268bd2
format-prefix = " "
```

**Comment by jaagr** [comment] 2017-05-22 18:18
Seems to be an issue with the `<bar>` tags then. Will look into it.

**Comment by jfchevrette** [comment] 2017-07-05 20:53
I have the same issue, however this also occurs even if brightness is not set to the max.

My config is here: https://github.com/jfchevrette/dotfiles/blob/master/polybar/.config/polybar/config

The color set on bar-fill-foreground overrides my global foreground color. If I set a foreground color on each individual modules, they take precedence over the one set on bar-fill-foreground.

I am running the latest commit available at the time of this post: b23ff17

**Comment by jfchevrette** [comment] 2017-07-05 20:57
I can confirm removing the <bar> tag from the xbacklight module can workaround the issue

**Comment by jfchevrette** [comment] 2017-07-05 21:03
Also occurring only on my laptop screen and not on my 2 other monitors which are running the same exact bar. Laptop monitor is a secondary display, primary is one of the external monitors.

**Comment by patrick96** [comment] 2017-09-08 11:10
This is an issue with a change that was made to how colors are handled. The issue is tracked in #639.
Closing

**Closed by patrick96** 2017-09-08 11:10 UTC
Labels: bug
