### ISSUE TITLE
polybar hangs after I change datetime by using ntpdate

### ISSUE THREAD

**Issue by bluephoen1x** [jaagr/polybar#1719] opened 2019-03-31 23:29 UTC
I am using Gentoo and i3 as the wm.
Today I suddenly found that my system clock is faster 1 hour and decided to enable ntp-client service and update the time. After I installed the new ntp-client service. That tool worked as expect and changed the system time to the correct one (I checked it from cli). But suddenly my backgroud music (spotify in chrome) stopped to play and the system time display in the polybar hadn't got update. I try to click the polybar and found it hangs. Strange~

**Comment by patrick96** [comment] 2019-04-01 08:57
Yeah, polybar can't really deal with the time moving backwards (see #857) because it uses non-monotonic time. Seems spotify has the same issue ;)

**Comment by patrick96** [comment] 2019-04-01 08:57
Duplicate of #857

**Closed by patrick96** 2019-04-01 08:57 UTC
