### ISSUE TITLE
Systray icons blury when "animated" icons play

### ISSUE THREAD

**Issue by Hacksaurus** [jaagr/polybar#1459] opened 2018-10-08 05:05 UTC
Whenever I connect to wifi using the networkmanager-applet, usually small animations play of the wifi symbol going up and down and what not. But for some sort of reason its all blury and no animation plays. You can see it has the similar affect to my pasystray icon too when I change volume.
![screenshot_2018-10-07_22-02-50](https://user-images.githubusercontent.com/24832107/46593044-15302680-ca7d-11e8-9e01-0fa66ced2b84.png)

**Comment by NBonaparte** [comment] 2018-10-08 22:50
Duplicate of  #1440. This has been happening recently, for some reason the background isn't cleared and new icons are drawn over the old ones resulting in blobs. However I haven't had much time to look into this issue.

**Closed by NBonaparte** 2018-10-08 22:50 UTC
