### ISSUE TITLE
Bar offset not applying

### ISSUE THREAD

**Issue by devonryder** [jaagr/polybar#597] opened 2017-05-29 18:21 UTC
I am trying to center my bar and the offsets do not seem to be applying. I am using `offset-x` and `offset-y` and neither appear to be applying. The bar simply stays to the left of the display.

**Config**
```
[bar/main]
monitor = DP-1

width = 90%
height = 33
offset-x = 10%
offset-y = 50
radius = 16
fixed-center = true
```

**Comment by TonCherAmi** [comment] 2017-05-29 18:31
Try setting `override-redirect` to `true`

**Comment by devonryder** [comment] 2017-05-29 23:52
@TonCherAmi This makes the bar flow over the other windows with the right side being off the screen.

**Comment by TonCherAmi** [comment] 2017-05-31 21:10
@devonryder look at `wm-restack` option in the [wiki](https://github.com/jaagr/polybar/wiki/Configuration) and try decreasing your `offset-x`.

**Comment by devonryder** [comment] 2017-06-04 15:01
@TonCherAmi with just `override-redirect = true` my offsets apply but the bar is over my windows. When I then add `wm-restack = i3` the windows now overlap my bar. 

Some additional info: I am running `i3-gaps` on a `2560x1440` monitor. My monitor setting reads exactly `monitor = DP-1` as defined from the output of `xrandr -q | grep " connected" | cut -d ' ' -f1`.

**Comment by TonCherAmi** [comment] 2017-06-08 18:15
@devonryder well, I get the same behavior, not sure whether it is intended or not though. I suppose @jaagr should know for sure.

**Comment by jaagr** [comment] 2017-06-09 09:42
This is "intended" as it is a limitation on how bar works in i3. You can't have a bar that isn't maximized width wise unless you use override redirect but then the top padding won't be applied. The hackish workaround to this is to fake the offset by using a transparent border.

**Comment by devonryder** [comment] 2017-06-24 15:56
@jaagr So, offset does not work in i3 correctly at all? The option is to do said border hack?

**Comment by NBonaparte** [comment] 2017-09-05 18:53
Marking this as wontfix, as this is caused by i3.

**Closed by NBonaparte** 2017-09-05 18:53 UTC
Labels: wontfix

**Comment by AlexD70** [comment] 2022-10-28 16:37
If you use i3-gaps you guys could increase gaps where polybar should be.
