### ISSUE TITLE
Allow fixed-width modules or force monospace font

### ISSUE THREAD

**Issue by nlgranger** [jaagr/polybar#490] opened 2017-03-17 12:39 UTC
Most icon fonts are not monospace, so when an icon/glyph changes in the bar, it may change the width of the module and move its neighbours.
Is there any way to force glyphs or modules to have a specified width?

(btw: congratulation for your awesome work!)

**Comment by jaagr** [comment] 2017-03-17 13:27
Hi and thank you!

I'm using a monospaced icon font myself so it's up to you. There's alot of them out there.

**Comment by dazWiLLiE** [comment] 2017-05-01 21:37
I have to ask since I'm just now also trying to have modules with fixed width..

What's up with the min and max token then? I thought that if you specify the same value of min and max the module would be fixed.. but that didn't work. For example, network and cpu modules still shrinks and expands (%downspeed:9:9%, %percentage:3:3%).

**Comment by patrick96** [comment] 2018-05-26 21:38
Closing this. 

Everything in polybar is done on a per character basis and this is most likely gonna stay this way. This means you need to use monospaced fonts or things will be very inconsistent, as you already explained.
Limiting a module to a certain amount of pixels (not characters) would be a real big hassle to configure, the user would have to tinker and figure out a good width, each time they change the contents of the module or any of the fonts. And I don't think we can force non-monospaced fonts to be monospaced.

As for @dazWiLLiE's problem, those tokens work fine for me and always keep the token contents 9 or 3 characters long respectively. If you are using a non-monospaced font, this will of course not always be the same width in terms of pixels.

**Closed by patrick96** 2018-05-26 21:38 UTC
Labels: enhancement

**Comment by GrantFinnegan** [comment] 2019-01-27 04:41
Unless the documentation for the token length bounding is incorrect, (which seems very likely given how bare bones it is), I can verify the problem experienced by @dazWiLLiE isn't a lie/hallucination, even if @patrick96 happens to not experience it themselves.
Tested by modifying default config per the wiki's documentation
Tested on arch linux, i3-gaps
Fonts used: defaults used in the example config
xbacklight, pulseaudio, and battery modules tested
all three failed to maintain a minimum width
I used the wiki's documentation on tokens, and have pasted it in it's entirety below for reference because it is so minimal. I've also noted some lines that are possible causes of this issue due to ambiguity in syntax

> label = %token% (really not sure what this is trying to convey)
> 
> ; Set value min width (I have to guess that this is supposed to mean "set the min width of the token")
> ; If the min-width begins with a `0`, the string will be zero-padded
> label = %token:3%
> 
> ; Set value max width (again, I have to guess that this is supposed to say "set the max width of the token")
> ; NOTE: the length of the token includes suffixes appended internally (KB/s, %, etc.)
> label = %token:0:10%
> 
> ; Specify suffix to be used if truncated to max width
> label = %token:0:10:...%
> label = %token:0:10:---%

Using the first example given does not work to limited the min width of the token. Here are the exact lines of the config file for the modules that I tested.
xbacklight: label = %percentage:3%%
battery: label-charging = %percentage:3%%
pulsaudio: label-volume = VOL %percentage:3%%

Setting a max width using the second and third examples does successfully truncate the tokens when they become too large, but they still fail to maintain a minimum width.
The wiki mentions that preceding "the min-width" with a 0 will make it zero padded. I considered the possibility that there might be no default padding character, and therefore the wiki was just in error for giving an example which did not specify a padding character, and therefore would be useless. So I tried putting 0 before the min width, however that just sets the min width to 0, and the max width to the previous min width.
Even though the wiki makes no mention of it being a possibility, I tried using several other, non-numerical padding characters (-_ and space). This did fix the issue with using 0, but it still did not maintain a minimum size.
I also tried putting the padding character after the truncation suffix, however that just gets interpreted as part of the truncation suffix. (for example at 100% "%percentage:2:2:...:0%%" displays as "10...:0%").
I can include screenshots if this issue is still believed to be not be real. And I'd be willing to create a separate issue for this. I just posted this here because this is the thread where the issue was brought up, and also where it was dismissed as not existing.

Also, on the original topic of this thread, fixed width modules wouldn't necessarily require dynamic font resizing. You could fake it by having dynamic module margins, or fixed per-module alignment at a pixel level instead of just left, center, and right. Although, those also seem like they could be real headaches to implement.

**Comment by patrick96** [comment] 2019-01-27 08:59
@GrantFinnegan Thanks for being thorough. All reports that we had about the minsize not working were because non-monospaced fonts were used. After I failed to reproduce the issue by @dazWiLLiE, I closed this ticket because the original issue was addressed and I suspected that non-monospaced fonts were used here as well (because that's what this issue originally was about).

I am still for the life of me unable to reproduce the issues that you have. Some clarifications about tokens:

* The default padding character for tokens that have fewer than min-width characters is the space character
* `%percentage:03:4%` will make the token have a min width of 3 and a max width of 4 and it will be zero-padded to the left.
* There is no way to specify other padding characters

>  Fonts used: defaults used in the example config

Because of this I still suspect this being a non-monospaced font issue because the fonts in the sample config may not be recognized on your system because unfortunately font names are not consistent across distros. You can check which fonts polybar loads by running it additionally with the `-l info` argument (see the [Wiki](https://github.com/jaagr/polybar/wiki/Fonts#freetype-fonts)).

Though if this is indeed not a monospaced font related issue I would appreciate you opening a new issue. If possible include screenshots as well as the entire config used so that we can also reproduce this.
