### ISSUE TITLE
thermal zone question

### ISSUE THREAD

**Issue by helionmelion** [jaagr/polybar#404] opened 2017-02-01 13:02 UTC
the below command does not work:
`for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done`

but this works:
`for i in /sys/class/thermal/cooling*; do echo "$i: $(<$i/type)"; done`
and its results:
/sys/class/thermal/cooling_device0: Processor
/sys/class/thermal/cooling_device1: Processor
/sys/class/thermal/cooling_device2: Processor
/sys/class/thermal/cooling_device3: Processor
/sys/class/thermal/cooling_device4: Processor
/sys/class/thermal/cooling_device5: Processor
/sys/class/thermal/cooling_device6: Processor
/sys/class/thermal/cooling_device7: Processor
/sys/class/thermal/cooling_device8: intel_powerclamp

i tried to change "thermal_zone = 0" for "cooling_device = 0" but with no results. What i have to do? thanks

**Comment by jaagr** [comment] 2017-02-01 14:29
A module update is required for this to work.

**Comment by kajzersoze** [comment] 2017-04-28 15:59
Same problem here, still no update ?

**Comment by jaagr** [comment] 2017-04-28 16:27
This can be fixed by changing `SETTING_PATH_TEMPERATURE_INFO` when building the project, for example:

~~~ sh
$ cmake -DSETTING_PATH_TEMPERATURE_INFO="/sys/class/thermal/cooling_device%zone%/temp" ..
~~~

**Comment by kajzersoze** [comment] 2017-04-28 18:55
Right, the problem is that there is no temp in that case.
Getting this error :
`error: Disabling module "temperature" (reason: The file '/sys/class/thermal/cooling_device0/temp' does not exist)`

Dunno how it is with thermal_zone but here's ls output of cooling, if it helps :
```
$ ls -la /sys/class/thermal/cooling_device0/                                                                                                                                                  
total 0
drwxr-xr-x 3 root root    0 Apr 26 14:24 .
drwxr-xr-x 4 root root    0 Apr 26 14:24 ..
-rw-r--r-- 1 root root 4096 Apr 27 01:49 cur_state
lrwxrwxrwx 1 root root    0 Apr 27 01:50 device -> ../../../LNXSYSTM:00/LNXCPU:00
-r--r--r-- 1 root root 4096 Apr 27 01:50 max_state
drwxr-xr-x 2 root root    0 Apr 27 01:50 power
lrwxrwxrwx 1 root root    0 Apr 27 01:50 subsystem -> ../../../../class/thermal
-r--r--r-- 1 root root 4096 Apr 27 01:50 type
-rw-r--r-- 1 root root 4096 Apr 26 14:24 uevent
```

**Comment by jaagr** [comment] 2017-04-28 18:59
What kernel are you using?

**Comment by kajzersoze** [comment] 2017-04-28 18:59
4.9.16

**Comment by x70b1** [comment] 2017-04-28 19:46
> Getting this error :
> `error: Disabling module "temperature" (reason: The file '/sys/class/thermal/cooling_device0/temp' does not exist)
> `

A cooling device is not a temp sensor. There is nothing to to found.
Look at this: https://github.com/01org/thermal_daemon/issues/60

A cooling device could be a passive element.

**Comment by jaagr** [comment] 2017-04-28 19:48
@kajzersoze How are you reading the CPU temperature?

**Comment by kajzersoze** [comment] 2017-04-28 19:56
Reading like this :
```
[module/cputemp]
type = custom/script
exec = echo `sensors -A | grep -oP '^CPU Te.+?  \+\K\d+' | awk '{k+=$1}END{print k/NR}'`°
interval = 10
format-underline = #f04242
format-foreground = #fffdd0
format-prefix = " "
format-prefix-foreground = #f04242
```

**Comment by jaagr** [comment] 2017-04-28 19:59
Do you have the name of that `sensors` utility? Then I could have a look on how they checks the values and we could maybe patch the polybar module to support it as well.

**Comment by kajzersoze** [comment] 2017-04-28 20:01
Package is lm-sensors.
You just type `sensors `in the terminal and it will output various info.
I was just greping temp from it.

**Comment by kobayash1** [comment] 2017-06-12 17:22
Using the default `[module/temperature]` from the installed config.  The temperature displayed is the same static one I get from `acpi -t`.

Perhaps we could consider retrieving the core temperatures the way `conky` does it?  It references the actual values in `/sys/devices/platform/coretemp.0/hwmon/hwmonX/tempY_input` where X is usually some random number between 0-3 that's generated based on kernel race situations if I understand correctly and where Y is the core, depending on how many cores you have.

A way to do this natively without having to use a `custom/script` would probably be ideal.  I suppose we could simply edit the flag manually when compiling, but the binary as it stands now (at least on Arch) definitely does not work as intended.  Plus, being an Arch noob, I don't know how to compile programs from source.  :)

**Closed** 2017-08-29 22:10 UTC

**Comment by yuceltoluyag** [comment] 2019-08-19 13:24
same error
5.2.9-arch1-1-ARCH
polybar -v
polybar 3.4.0
