### ISSUE TITLE
Backlight and Volume sliders not displayed properly.

### ISSUE THREAD

**Issue by Morganamilo** [jaagr/polybar#1047] opened 2018-02-23 12:32 UTC
Recently after an update (I'm not sure if polybar itself updated or just other packages such as libraries) Polybar now no longer displays the Volume or backlight slider it instead looks like this.
![image](https://user-images.githubusercontent.com/16593899/36594154-ec5a0d6a-1894-11e8-8504-e7df82c79efd.png)
The issue seems mostly visual as scrolling over and clicking the volume work fine. The 'sound muted' message also displays fine.
![image](https://user-images.githubusercontent.com/16593899/36594200-2112d780-1895-11e8-9e41-41589010cf03.png)
This problem also happens on the default example bar.

Running  polybar-3.1.0-2 from the AUR.

**Comment by patrick96** [comment] 2018-02-23 12:42
Probably a duplicate of #1044. Check your [Fonts](https://github.com/jaagr/polybar/wiki/Fonts#debugging-font-issues)

**Comment by Morganamilo** [comment] 2018-02-23 12:42
After installing polybar-git-3.1.0.r63.g2f62a6f-1 the problem persists.

**Closed by patrick96** 2018-02-23 12:42 UTC
Labels: font
