### ISSUE TITLE
Add left/right click events for date

### ISSUE THREAD

**Issue by hiemanshu** [jaagr/polybar#306] opened 2017-01-04 15:24 UTC
I want to be able to click the date and have it open a simple calendar (gsimplecal). The date module doesn't currently listen to events. I know I can use the custom module to do this, but I'd rather use the date module for this.

**Comment by d125q** [comment] 2017-01-05 12:17
I think that every module should have custom click handlers rather than predefined ones...

**Comment by jaagr** [comment] 2017-01-07 11:49
I think we should keep the predefined handlers but make it possible to override them with custom ones.

**Comment by jaagr** [comment] 2017-01-09 14:54
Closing, duplicate of #273

**Closed by jaagr** 2017-01-09 14:54 UTC
