### ISSUE TITLE
Tray overlays everything

### ISSUE THREAD

**Issue by coderobe** [jaagr/polybar#914] opened 2017-12-19 16:46 UTC
When running polybar under xfwm4, the tray area appears to overlay all windows (including fullscreen applications).

Version info: 
```
polybar 3.1.0

Features: +alsa +curl -i3 -mpd -network
```

**Comment by NBonaparte** [comment] 2017-12-19 19:55
Duplicate of #425.

**Closed by NBonaparte** 2017-12-19 19:55 UTC
