### ISSUE TITLE
Tray covers panel elements

### ISSUE THREAD

**Issue by alexozer** [jaagr/polybar#878] opened 2017-12-03 21:07 UTC
When loading a polybar with a tray, the following happens:

* The tray loads with all elements aligned to the right, without a panel
* The tray on the right side appears
* The rest of the panel shifts down, but less than the amount of the size of the tray, so the tray covers some of the panel.

This is fairly inconsistent as well; roughly a quarter of the time I start polybar this does not happen.

![image](https://user-images.githubusercontent.com/2074322/33529837-095360ce-d844-11e7-8cc9-84a0a6283681.png)

[My config](https://gist.github.com/alexozer/c14426ff05c53f5907e8c99b3bee82b5)

**Comment by patrick96** [comment] 2017-12-03 21:41
Looks like a duplicate of #591. At some point we're going to do an overhaul of the tray and then we'll fix, but for now we'll have to live with this. Your best bet would probably be to just add a text module at the rightmost position with a few blank spaces.

**Closed by patrick96** 2017-12-03 21:41 UTC
