### ISSUE TITLE
xwindow breaks when displaying certain website titles (possibly pipe character)

### ISSUE THREAD

**Issue by 97-109-107** [jaagr/polybar#465] opened 2017-02-26 20:06 UTC
Using the *xwindow* module
```
[module/xwindow]
type = internal/xwindow
label = %title:0:45:...%
```
When pointing a webbrowser to pages of certain title, the output of lemonbar breaks - it loses it's content, the color goes to black, but it remains running and nothing appears in the logs.

The WM_TITLE that managed to cause this behaviour was:
> Beautiful panoramic Cubist drawings of China’s urbanized landscape | Dangerous Minds
I tested it with some other titles, none of them resulted in the same
behaviour - I assume this is caused by the pipe character.

- - - 
For *qutebrowser* users, the title can be disabled via ``set ui window-title-format qutebrowser``

**Comment by skystrife** [comment] 2017-02-26 21:06
Dupe of #393?

Can you try the latest git revision?

**Closed** 2017-02-26 21:57 UTC
