### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by Norbzilla** [jaagr/polybar#605] opened 2017-06-04 04:42 UTC
I've been trying to install polybar from the Arch User Repository, but each time I keep getting this error message.

`/tmp/yaourt-tmp-norbzilla/aur-polybar/src/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:147:57: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>   i3_recv(const int32_t  sockfd) throw (invalid_header_error, eof_error);
                                                         ^~~~~
In file included from /tmp/yaourt-tmp-norbzilla/aur-polybar/src/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/tmp/yaourt-tmp-norbzilla/aur-polybar/src/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:163:131: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 int32_t  sockfd, const ClientMessageType  type, const std::string&  payload = std::string()) throw (invalid_header_error, eof_error);
                                                                                              ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [lib/i3ipcpp/CMakeFiles/i3ipc++.dir/build.make:63: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:440: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build polybar.`

I don't know if it's my computer or not, but I wanted to let you know.

**Comment by justinnichols** [comment] 2017-06-04 04:57
It's not just your computer.  It's occurring on my freshly installed Arch Linux + Gnome/GDM + i3 install.

**Comment by Dupond** [comment] 2017-06-04 06:40
I think this is due to GCC that has been updated five days ago. The current version is now 7.1.1.
From [url=https://www.reddit.com/r/archlinux/comments/6e0g7c/gcc_711_is_in_core/]this thread on reddit[/url] :
[quote]So if you are having troubles building polybar after that - switch to clang temporary. Install clang and add this to the PKGBUILD before cmake in the build() section:
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++

this might work for other packages too, as a workaround for everything that relies on now deprecated stuff in GCC[/quote]

**Comment by aurieh** [comment] 2017-06-04 16:32
@Dupond Yeah, add those two lines to the top of the `build` function/procedure in the PKGBUILD.

**Comment by justinnichols** [comment] 2017-06-04 17:23
This indeed allowed the source to be built and the package from the AUR to be installed.  Thanks.

**Comment by LinuxNoob24** [comment] 2017-06-04 17:50
> So if you are having troubles building polybar after that - switch to clang temporary. Install clang and add this to the PKGBUILD before cmake in the build() section:
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++

This sounds really good - I have developed a useful Polybar on a VM but can not now install it to my laptop, I guess this is the 'Linux Experience' ;-).

Could I ask for a little more detail (I really am a Linux noob!) - where would I find the PKGBUILD?

**Comment by aurieh** [comment] 2017-06-04 18:31
@LinuxNoob24 If you use pacaur or yaourt, it will ask you if you want to edit PKGBUILD, select `Y` or `yes`. If you install AUR packages manually (via a `git clone`) there'll be a PKGBUILD inside your cloned repo. Edit that with your favorite editor and go through the rest of the steps [at the arch wiki](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages).

**Comment by LinuxNoob24** [comment] 2017-06-04 18:38
> @LinuxNoob24 If you use pacaur or yaourt, it will ask you if you want to edit PKGBUILD, select Y or yes. If you install AUR packages manually (via a git clone) there'll be a PKGBUILD inside your cloned repo. Edit that with your favorite editor and go through the rest of the steps at the arch wiki.

@aurieh - that is brilliant - thank you so much for your help, I can now complete my project.

**Comment by jaagr** [comment] 2017-06-07 15:43
@Dupond yeah, I will fix the issues but I currently don't have much time over for it. Might be better to update the `PKGBUILD` and add `clang` as a dep until its been fixed.

**Comment by jaagr** [comment] 2017-06-07 15:54
For you who are installing `polybar` using the AUR; I have updated the `PKGBUILD` so that `clang` will be used until the gcc issues have been fixed.

**Comment by jaagr** [comment] 2017-06-07 15:56
Closing as a duplicate of #572

**Closed by jaagr** 2017-06-07 15:56 UTC

**Comment by shahules** [comment] 2017-11-05 03:49
ERROR: A failure occurred in build().
    Aborting...
ERROR: Makepkg was unable to build polybar.
i got this error when trying to install polybar on my freshly installed manajro i3.what am i supposed to do?

**Comment by patrick96** [comment] 2017-11-05 05:43
@shahules Please don't post in a closed issue unless it's related. Open a new issue with more information (output of `makepkg` or `cmake` and `make`)
