### ISSUE TITLE
i3 module is empty (no error) when "pin-workspaces" is true

### ISSUE THREAD

**Issue by lcthums** [jaagr/polybar#814] opened 2017-10-22 08:11 UTC
I'm running i3-gaps-next-git and polybar-git on Arch Linux (AUR packages), and on my 3 monitor setup, if I set pin-workspaces to True, the i3 module is completely hidden/empty (on all 3 bars), but no error is displayed.

The launch script is launched by i3 and has a 1s sleep before executing polybar to guarantee the bars are launched after i3 (saw someone recommending that in another thread).

How can I debug? "-l info" says nothing relevant

```
> $ polybar -v                                                                            
polybar 3.0.5-74-g5737156

Features: +alsa +curl +i3 +mpd +network
```

My module config:
```

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

label-focused = %index%
label-focused-background = ${module/bspwm.label-focused-background}
label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = ${module/bspwm.label-focused-padding}

label-unfocused = %index%
label-unfocused-padding = ${module/bspwm.label-occupied-padding}

label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

label-urgent = %index%
label-urgent-background = ${module/bspwm.label-urgent-background}
label-urgent-padding = ${module/bspwm.label-urgent-padding}

pin-workspaces = true 
```

Edit: I should make clear that running the bars with pin-workspaces = false displays all workspaces correcly

**Comment by patrick96** [comment] 2017-10-22 16:43
I'm unable to reproduce this on my machine with the same packages and config but only two monitors.
Can you please post your whole config, the output of `polybar -vvv` as well as the whole output of `polybar` with the `-l trace` argument (or `-lt info` if that doesn't work). Can you also post the code you use to start the bar on your three monitors.

This may be the same as or related to the issue in #499

**Comment by lcthums** [comment] 2017-10-22 21:56
Of course, here is the information requested:

```
> $ polybar -vvv   
polybar 3.0.5-74-g5737156

Features: +alsa +curl +i3 +mpd +network

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro
```

```
> $ polybar -lt info main                                                                                                                                                                
* Loaded /home/luancristian/.config/polybar/config
* Loaded monitor DP-4 (1920x1080+1080+224)
* Found matching X resource "color0" (value=#1b1918)
* Found matching X resource "color7" (value=#a8a19f)
* Bar geometry: 1920x24+1080+1280
* Found matching X resource "color3" (value=#d5911a)
* Found matching X resource "color1" (value=#f22c40)
* Found matching X resource "color3" (value=#d5911a)
* Found matching X resource "color1" (value=#f22c40)
* Found matching X resource "color3" (value=#d5911a)
* Found matching X resource "color10" (value=#5ab738)
* Found matching X resource "color10" (value=#5ab738)
* Found matching X resource "color10" (value=#5ab738)
* Found matching X resource "color10" (value=#5ab738)
* Found matching X resource "color10" (value=#5ab738)
* Found matching X resource "color11" (value=#d5911a)
* Found matching X resource "color1" (value=#f22c40)
* Found matching X resource "color7" (value=#a8a19f)
* Found matching X resource "color5" (value=#6666ea)
* Found matching X resource "color12" (value=#407ee7)
* Found matching X resource "color5" (value=#6666ea)
* Found matching X resource "color5" (value=#6666ea)
* Starting application
* Starting module/i3
* Starting module/xwindow
* Starting module/volume
* Starting module/wlan
* Starting module/date
* Starting module/powermenu
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=8)
* Configured DPI = 96x96
* Loaded font "Anonymous Pro:fontformat=truetype:size=11:antialias=true" (name=Anonymous Pro, offset=0, file=/usr/share/fonts/TTF/Anonymous Pro.ttf)
* Loaded font "unifont:fontformat=truetype:size=8:antialias=false" (name=DejaVu Sans, offset=0, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Loaded font "Wuncon Siji:pixelsize=11" (name=Wuncon Siji, offset=1, file=/usr/share/fonts/misc/siji.pcf)
* Bar window: 0x1000002
* Activating tray manager
* Tray window: 0x1000006
* module/i3: Rebuilding cache
* module/xwindow: Rebuilding cache
* module/volume: Rebuilding cache
* module/wlan: Rebuilding cache
* module/date: Rebuilding cache
* module/powermenu: Rebuilding cache
* Redrawing bar window
* Notifying pending tray clients
* Processing docking request from 0x08001ac
* Processing docking request from 0x0e00367
* Processing docking request from 0x3200036
* Redrawing bar window
* Redrawing bar window
* Redraw tray container (id=0x1000006)
* Redrawing bar window
* Redraw tray container (id=0x1000006)
* Redraw tray container (id=0x1000006)
* Redraw tray container (id=0x1000006)
* Redraw tray container (id=0x1000006)
* module/wlan: Rebuilding cache
warn: Termination signal received, shutting down...
```

```
> $ cat .config/polybar/launch.sh                                                                                                                                                        
sleep 1;

killall -q polybar;

while ps aux | grep -qx polybar;
    do sleep 1;
done;

polybar portrait &
polybar main &
polybar right &
```

```
> $ xrandr                                                                                                                                                                               
Screen 0: minimum 8 x 8, current 4680 x 1920, maximum 32767 x 32767
DVI-D-0 connected 1080x1920+0+0 right (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080     60.00*+
   1680x1050     59.95  
   1440x900      59.89  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x720      60.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected 1680x1050+3000+254 (normal left inverted right x axis y axis) 474mm x 296mm
   1680x1050     59.95*+
   1600x1200     60.00  
   1440x900      59.89  
   1400x1050     59.98  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x720      60.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 connected primary 1920x1080+1080+224 (normal left inverted right x axis y axis) 531mm x 299mm
   1920x1080     60.00 + 144.00*  119.98    99.93    59.94    50.00  
   1680x1050     59.88  
   1440x900      59.90  
   1280x1024     75.02    60.02  
   1280x720      60.00    59.94    50.00  
   1024x768     119.99    99.97    75.03    70.07    60.00  
   800x600      119.97    99.66    75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480      119.52    99.77    75.00    72.81    59.94    59.93  
DP-5 disconnected (normal left inverted right x axis y axis)
```

Polybar config: https://pastebin.com/sjHAJ3WU

**Comment by daf** [comment] 2017-10-30 15:18
I have the same issue on my 3 monitor setup.  I have `pin-workspaces = false` on my main monitor setup, and that works fine.  Setting it to that on the other bars also works fine. 

(I've noticed it does crash on mousewheel over the i3 module but not sure if that's related or just an artifact of the sample config I haven't touched yet.)

```
~ -> polybar -vvv
polybar 3.0.5

Features: +alsa +curl +i3 -mpd -network

X extensions: +randr (-monitors) -render -damage -sync -composite +xkb +xrm

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: 
```

```~ -> polybar -lt info left
* Loaded /home/daf/.config/polybar/config
* Loaded monitor DP-2 (1200x1920+0+0)
* Bar geometry: 1200x27+0+0
* Starting application
* Starting module/i3
* Starting module/date
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=4)
* Configured DPI = 96x96
* Loaded font "Fantasque Sans Mono:pixelsize=10" (name=Fantasque Sans Mono, offset=1, file=/home/daf/.fonts/FantasqueSansMono-Regular.ttf)
* Loaded font "unifont:fontformat=truetype:size=8:antialias=false" (name=Unifont, offset=0, file=/usr/share/fonts/truetype/unifont/unifont.ttf)
* Loaded font "FontAwesome:pixelsize=10" (name=FontAwesome, offset=1, file=/usr/share/fonts/opentype/font-awesome/FontAwesome.otf)
* Loaded font "siji:pixelsize=10" (name=Siji, offset=1, file=/home/daf/.fonts/siji.pcf)
* Bar window: 0x0a00002
* Disabling tray manager (reason: missing `tray-position`)
* module/i3: Rebuilding cache
* module/date: Rebuilding cache
* Redrawing bar window
```

```
~ -> xrandr
Screen 0: minimum 8 x 8, current 6240 x 2160, maximum 32767 x 32767
DVI-D-0 disconnected (normal left inverted right x axis y axis)
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 connected primary 1200x1920+5040+0 left (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95*+
   1920x1080     60.00  
   1680x1050     59.95  
   1600x1200     60.00  
   1280x1024     60.02  
   1280x960      60.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected 1200x1920+0+0 right (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95*+
   1920x1080     60.00  
   1680x1050     59.95  
   1600x1200     60.00  
   1280x1024     60.02  
   1280x960      60.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 connected 3840x2160+1200+0 (normal left inverted right x axis y axis) 600mm x 340mm
   3840x2160     60.00*+  30.00  
   2560x1440     59.95  
   1920x1080     60.00    59.94  
   1600x900      60.00  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94  
   1152x864      59.96  
   1024x768      60.00  
   800x600       60.32  
   720x480       59.94  
   640x480       59.94    59.93  
DP-5 disconnected (normal left inverted right x axis y axis)
```

```

~ -> cat ~/.i3/polybar.sh 
#!/usr/bin/env sh

killall -q polybar

while pgrep -x polybar >/dev/null; do sleep 1; done

polybar main &
polybar left &
polybar right &
```

Polybar config: https://gist.github.com/daf/dd00a2e4ff6492c5c94efef8dab80c31

**Comment by lcthums** [comment] 2017-10-30 17:04
My issue has since gone away! I have no idea what changed but I tried setting pin-workspaces back to true and it worked this time. I am positive I rebooted many times during testing and I am running the exact same configs, so that couldn't be it.

As @daf pointed out, when I scrolled on the bar it used to crashed, that also doesn't happen anymore.

**Comment by daf** [comment] 2017-10-30 20:35
Digging a bit - when `pin-workspaces = true`, it filters the list of workspaces (from i3) on the `output` field that i3 responds with and wants them to line up with the bar's `monitor` setting.  On my setup, i3 is reporting outputs to be `xinerama-0` through `xinerama-2` whereas my monitor settings use more xrandr familiar names like `DP-0`/`DP-2`/`DP-4`.  This seems like i3 is wrong here and should be reporting by xrandr name.

**Comment by daf** [comment] 2017-11-10 20:56
Finally figured out I had a stray `force_xinerama = yes` in my i3 config - no wonder it was labeling them all with xinerama prefixes.  Removing that and this works for me again.

**Comment by patrick96** [comment] 2017-11-11 20:25
So I guess, we can close this.
If the problem comes back, please reopen

**Closed by patrick96** 2017-11-11 20:25 UTC
