### ISSUE TITLE
 Linking CXX static library libxpp.a

### ISSUE THREAD

**Issue by woopsi** [jaagr/polybar#1098] opened 2018-03-15 11:58 UTC
![screenshot from 2018-03-15 14-01-49](https://user-images.githubusercontent.com/24606015/37462014-202bb458-2859-11e8-9a6b-346bf327424e.png)
Seems a problem occurs from a cpp_client.py when i try to build from source because of a module.

Maybe the problem is because of python 3.6?

**Comment by patrick96** [comment] 2018-03-15 13:53
Duplicate of #1090 

Did you build from the AUR? If so, build `polybar` again with the newest PKGBUILD and in a clean directory. 
If not, either build against the latest commit, or if you want to build version 3.1.0, manually go into the `xpp` submodule and update it before building:
```bash
cd lib/xpp
git fetch
git checkout master
```

**Closed by patrick96** 2018-03-15 13:53 UTC
Labels: build, duplicate

**Comment by Godje** [comment] 2018-05-30 09:44
Had similar issue on Ubuntu 18.04.
Removed `xcb-proto 1.13-1` and manually install `xcb-proto 1.11`
Rerun the ./build.sh and everything went as it should
