### ISSUE TITLE
xwindow: issues when focus changes the monitor/desktop, regression (bspwm)

### ISSUE THREAD

**Issue by quite** [jaagr/polybar#265] opened 2016-12-22 11:04 UTC
When shifting focus between two windows, each on its own monitor, the xwindow
title does not *always* update. If I use the mouse, almost never. If I do it by
a command, like "bspc monitor -f next", a bit more often... I have one bar on
each monitor, and additionally the xwindow modules sometimes display different
titles!

Now I also noticed that I see similar problems when focus changes to a window
on a different desktop on the same monitor. Both the issue with updating and
with polybars showing different titles.

Normally I don't have my pointer follow focus, but I tried with `bspc config
pointer_follows_focus true` as well, but no change.

Shifting focus between windows on the same monitor and desktop does not
seem to trigger this at all.

If I build from b2e8428550 then I don't see any of this.

**Comment by jaagr** [comment] 2016-12-22 19:55
Seems to be caused by the bspwm module since it doesn't happen without it.

**Comment by quite** [comment] 2016-12-22 22:15
That's your observation, right? :)

**Comment by quite** [comment] 2016-12-22 22:41
Hm, with that commit xwindow seems to behave well, but none of the bars accept clicks/scrolls seems messed up

**Comment by jaagr** [comment] 2016-12-22 22:47
Yeah I'm working on it right now.

**Comment by jaagr** [comment] 2016-12-23 00:08
The issue should be fixed in current `HEAD`, please verify.

**Comment by jaagr** [comment] 2016-12-23 04:21
Current `HEAD` should be working as expected, please verify.

**Comment by quite** [comment] 2016-12-23 08:36
Yes, xwindow seems fine now. But no clicking/scrolling anywhere on any bar.

**Comment by jaagr** [comment] 2016-12-23 10:06
What compiler?

**Comment by quite** [comment] 2016-12-23 10:12
Michael Carlberg <notifications@github.com>, 2016-12-23 02:06:15 (-0800):
> What compiler?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jaagr/polybar/issues/265#issuecomment-268967091

-- The CXX compiler identification is Clang 3.8.1

ii  clang-3.8                             1:3.8.1-16
ii  lib32stdc++6                          4.9.2-10

And I cannot install new enough gcc on this machine.

**Comment by quite** [comment] 2016-12-23 10:14
```
polybar 2.4.1-1-g7ecd132 

Features: +alsa +curl -i3 +mpd +network 

Build type: Release
Compiler: /usr/bin/clang++
Compiler flags:  -Wall -Wextra -Werror -O3 -pedantic -pedantic-errors -ffunction-sections -fdata-sections
Linker flags:  -Wl,--gc-sections
```

**Comment by jaagr** [comment] 2016-12-23 11:23
`libstdc++-4.9.2`, retro...

**Comment by quite** [comment] 2016-12-23 11:35
Yeah, debian jessie. But, I saw now that polybar is linked like so:

	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f20991cb000)

ii  libstdc++6:amd64                      6.2.1-5

**Comment by jaagr** [comment] 2016-12-23 12:20
1cb8e45 should fix the click/scroll

**Comment by japhir** [comment] 2016-12-23 13:21
For me on Arch linux with i3 I have a very similar issue (so i'm not making a separate thingie). When I change focus from one monitor to the other, the "inactive" workspace (the one I previously focussed) icon is faded out entirely, while other workspaces that were not recently focused before switching focus from one screen to the other remain normal.

**Comment by jaagr** [comment] 2016-12-23 13:50
@japhir it's unrelated to this issue.. but this is probably because you are using a different style for `label-visible` which is the state the focused workspace on the non-focused monitor will be in when you switch monitor.

**Comment by japhir** [comment] 2016-12-23 15:00
@jaagr whoops you're right. Thanks for the prompt reply that helped me fix the issue! :+1:

**Comment by jaagr** [comment] 2016-12-23 21:42
@quite fixed the input handling... would you mind building the latest patch release and verify

**Comment by quite** [comment] 2016-12-27 18:23
Clicking/scrolling all work, but currently I don't have access to a monitor
to verify that the regression is still corrected...

**Comment by quite** [comment] 2016-12-31 07:33
Running 2.4.4 on two monitors, I think we're good

**Closed** 2017-01-09 14:51 UTC
Labels: bug, confirmed
