### ISSUE TITLE
The volume module stops to reflect the sound changes when changing an output device

### ISSUE THREAD

**Issue by Shamaoke** [jaagr/polybar#799] opened 2017-10-10 18:01 UTC
I have a laptop with embedded speakers. I also have a portable USB sound card, which I use as an output device for my headphones. For the sound output PulseAudio is used, which I suppose uses the ALSA sound system internally.

I added the polybar volume module on the panel. I also assigned hotkeys to increase and decrease the sound volume using a facility provided by the window manager. When pressing the keys the system performs `amixer set Master 1%+` and `amixer set Master 1%-` shell commands. I use this to control the sound volume.

I use the following configuration file (excerpt):

    [bar/sample]
    modules-right = volume

    [module/volume]
    type = internal/volume

The problem is, when I run polybar its volume module is being bound to the portable sound card, if it's plugged, and displays the volume changes only for this device. If I unplug it, the sound output is switched to the embedded speakers but the volume changes aren't displayed on the bar. The numbers stop to change but the volume itself is increased and decreased without any problems.

When I plug the portable sound card back into the laptop, the sound output is switched to the device, the volume module captures this event and starts to reflect the volume changes again.

Why doesn't the volume module reflect changes of the sound volume when changing an output device? What can be done in this regard?

**Comment by NBonaparte** [comment] 2017-10-10 18:11
We have a Pulseaudio module in the requests (#779). Until it is merged, you could try using the Pulseaudio script on the wiki.

**Comment by patrick96** [comment] 2017-10-12 12:28
The volume module only supports a single soundcard and can't automatically switch to another one, once it is connected. Either use some solution with pulseaudio as mentioned by NBonoaparte or have one module per soundcard

**Comment by NBonaparte** [comment] 2017-11-02 23:43
Just found #472 which this is a duplicate of. Closing in favor of that issue.

**Closed by NBonaparte** 2017-11-02 23:43 UTC
