### ISSUE TITLE
MPD module is showowing title as "untitled track" when artist is unknow

### ISSUE THREAD

**Issue by g3t0r** [jaagr/polybar#815] opened 2017-10-22 09:21 UTC
MPD module is showowing title as "untitled track" when artist is unknow

```
[module/mpd]
type = internal/mpd

host = 127.0.0.1
port = 6600
interval = 2
label-song =  %title% - %artist%
label-offline = 🎜 mpd is offline
format-online = <label-song> 

icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 

label-song-maxlen = 25
label-song-ellipsis = true

```
![przechwycenie obrazu ekranu_2017-10-22_11-17-31](https://user-images.githubusercontent.com/17712077/31860467-ca902e20-b71a-11e7-8499-50015a721e0d.png)

![przechwycenie obrazu ekranu_2017-10-22_11-18-08](https://user-images.githubusercontent.com/17712077/31860473-dbbf53ec-b71a-11e7-8c3f-17b2085787e8.png)

**Comment by patrick96** [comment] 2017-10-22 20:54
Duplicate of #766 
Please give your input on how you would like to have this handled over there

**Comment by NBonaparte** [comment] 2017-10-22 21:12
This looks different than #766, as it appears to be a bug that shows `untitled track` when it should be `Scandroid - Eden.mp3`.

@g3t0r could you give more information on what version you're on (polybar, mpd, libmpdclient) and what distro you're using?

**Comment by patrick96** [comment] 2017-10-23 07:32
Sorry totally misread that.

From the screenshot it seems to me that the mp3 file doesn't have a title set and `ncmpcpp` just displays the name of the file whereas polybar displays "unkown artist"

**Comment by g3t0r** [comment] 2017-10-23 15:33
@NBonaparte  I'm using Manjaro, mpd version is 0.20.10, libmpdclient 2.11-1, polybar 3.0.5-74-g5737156

**Comment by NBonaparte** [comment] 2017-10-23 22:04
What does `mpc -f "%title% - %artist"` display?

**Comment by NBonaparte** [comment] 2017-10-24 05:12
Never mind, I reproduced this with tag-less files and it is as @patrick96 said. We could add a fallback which calls `mpd_song_get_uri(s)` and extracts the filename (similar to ncmpcpp), if you would like it as a feature.

**Comment by g3t0r** [comment] 2017-10-24 15:03
Sure, that would be great!

**Closed** 2017-11-09 05:12 UTC
Labels: enhancement
