### ISSUE TITLE
#aa[rrggbb] not working on i3 label-unfocused-foreground

### ISSUE THREAD

**Issue by jonathashenriques** [jaagr/polybar#169] opened 2016-11-16 20:38 UTC
I don't know why but, with my config the new formatting method (#00rrggbb) is not working only with the i3 label-unfocused-foreground.

> ;====================================================;
;						     ;
;   To learn more about how to configure Lemonbuddy  ;
;   go to https://github.com/jaagr/lemonbuddy	     ;
;						     ;
;   The README contains alot of information	     ;
;						     ;
;====================================================;

[settings]

[bar/Bar]
bottom = false
dock = false
width = 100%
height = 24
lineheight = 4
;border-top = 8
;border-bottom = 1
;border-left = 8
;border-right = 8
padding-left = 2
padding-right = 1
module-margin-right = 2
modules-left = i3 Spotify
modules-center = Xtitle
modules-right = Volume Clock Shutdown
tray-position = right
tray-background = ${bar/Bar.background}
tray-detached = true
tray-maxsize = 10
tray-offset-x = -179
tray-transparent = true
tray-padding = 2
background = #ffffff
font-0 = lemon-7,49262:style=Regular
font-1 = -wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1;1

[module/i3]
type = internal/i3
label-focused = 
label-focused-padding = 1
label-unfocused = 
label-unfocused-padding = 1
label-urgent = 
label-urgent-padding = 1
label-visible = 
label-visible-padding = 1
label-focused-foreground = #00rrggbb
label-unfocused-foreground = #80rrggbb

[module/Spotify]
type = custom/script
exec = ~/.config/lemonbuddy/Scripts/Spotify/Spotify.sh
interval = 5
maxlen = 40
ellipsis = true
scroll-up = xdotool key super+0
scroll-down = xdotool key super+z
format-padding = 1
format-foreground = ${bar/Bar.background}
format-background = #00rrggbb
format-overline = ${bar/Bar.background}
format-underline = ${bar/Bar.background}

[module/Xtitle]
type = custom/script
exec = xtitle -s
tail = true
maxlen = 40
ellipsis = true
format-foreground = ${bar/Bar.foreground}

[module/Volume]
type = internal/volume
master-mixer = Master
speaker-mixer = Speaker
headphone-mixer = Headphone
headphone-id = 1
label-muted = 
format-volume = <ramp-volume>
format-muted = <label-muted>
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-headphones-0 = 
ramp-headphones-1 = 
format-volume-foreground = #00rrggbb
format-muted-foreground = #00rrggbb
label-muted-foreground = #00rrggbb

[module/Clock]
type = internal/date
date = %a, %d %b | %H:%M
interval = 5
format-padding = 2
format-foreground = ${bar/Bar.background}
format-background = #00rrggbb
format-overline = ${bar/Bar.background}
format-underline = ${bar/Bar.background}

[module/Shutdown]
type = custom/script
exec = echo " "
click-left = shutdown now
click-right = reboot
click-middle = xdotool key super+shift+e
format-padding = 1
format-foreground = #00rrggbb

**Comment by jaagr** [comment] 2017-01-09 18:52
Closing as I can't reproduce the issue, please re-open if it's still valid.

**Closed by jaagr** 2017-01-09 18:52 UTC
