### ISSUE TITLE
System tray true transparency and more configuration option

### ISSUE THREAD

**Issue by Alkeryn** [jaagr/polybar#600] opened 2017-06-01 10:19 UTC
Well it would be nice for it to be able to have the same transparency and color as the rest of the bar and also true transparency instead of fake one 
plus it should be a module so we can choose its position in the bar

**Comment by NBonaparte** [comment] 2017-09-05 21:48
Duplicate of #382 and #314.

**Closed by NBonaparte** 2017-09-05 21:48 UTC
