### ISSUE TITLE
Bar does not show up, "background_manager: Failed to copy slice of root pixmap (XCB_MATCH (8))"

### ISSUE THREAD

**Issue by ixolius** [jaagr/polybar#1582] opened 2019-01-05 20:24 UTC
When trying to start polybar, it doesn't show up and I get the error:
`background_manager: Failed to copy slice of root pixmap (XCB_MATCH (8))`
There is a related issue, where a restart solved the problem. This does not work for me.

My config:

```dosini
[colors]
;background = ${xrdb:color0:#222}
background = #222
background-alt = #444
;foreground = ${xrdb:color7:#222}
foreground = #dfdfdf
foreground-alt = #555
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

[bar/standard]
;monitor = ${env:MONITOR:HDMI-1}
monitor-fallback=VGA-0
width = 100%
height = 27
;offset-x = 1%
;offset-y = 1%
radius = 6.0
fixed-center = false

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
line-color = #f00

border-size = 4
border-color = #00000000

padding-left = 0
padding-right = 0

module-margin-left = 1
module-margin-right = 2

font-0 = fixed:pixelsize=10;1
font-1 = unifont:size=8:antialias=false;0
font-2 = Wuncon Siji:style=Regular:pixelsize=10;1

modules-left = i3
modules-center =xwindow
modules-right = filesystem pulseaudio xkeyboard memory cpu eth date powermenu

tray-position = right
tray-padding = 2
;tray-transparent = true
;tray-background = #0063ff

;wm-restack = bspwm
;wm-restack = i3

;override-redirect = true

;scroll-up = bspwm-desknext
;scroll-down = bspwm-deskprev

;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev

cursor-click = pointer
cursor-scroll = ns-resize

locale = de_DE.UTF-8

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%
label-empty = <noname>

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-prefix-underline = ${colors.secondary}

label-layout = %layout%
label-layout-underline = ${colors.secondary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/filesystem]
type = internal/fs
interval = 60

mount-0 = /
mount-1 = /home
mount-2 = /home/ixolius/Austausch

label-mounted = %{F#0a81f5}%mountpoint%%{F-} : %percentage_used% %
label-unmounted = %mountpoint% : not mounted
label-unmounted-foreground = ${colors.foreground-alt}

[module/bspwm]
type = internal/bspwm

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-occupied = %index%
label-occupied-padding = 2

label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2

; Separator in between workspaces
; label-separator = |

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
enable-scroll = false
strip-wsnumbers = true

; Only show workspaces on the same output as the bar
;pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %name%
label-focused-background = ${module/bspwm.label-focused-background}
label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = ${module/bspwm.label-focused-padding}

; unfocused = Inactive workspace on any monitor
label-unfocused = %name%
label-unfocused-padding = ${module/bspwm.label-occupied-padding}

; visible = Active workspace on unfocused monitor
label-visible = %name%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %name%
label-urgent-background = ${module/bspwm.label-urgent-background}
label-urgent-padding = ${module/bspwm.label-urgent-padding}

; Separator in between workspaces
label-separator = |


[module/mpd]
type = internal/mpd
format-online = <label-song>  <icon-prev> <icon-stop> <toggle> <icon-next>

icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 

label-song-maxlen = 25
label-song-ellipsis = true

[module/xbacklight]
type = internal/xbacklight

format = <label> <bar>
label = BL

bar-width = 10
bar-indicator = |
bar-indicator-foreground = #fff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}

[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #f90000
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #4bffdc
label = %percentage_used%%

[module/wlan]
type = internal/network
interface = wlp1s5
interval = 3.0

format-connected = <ramp-signal> <label-connected>
format-connected-underline = #9f78e1
label-connected = %essid%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = ${colors.foreground-alt}

[module/eth]
type = internal/network
interface = enp3s0
interval = 3.0

format-connected-underline = #55aa55
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = %local_ip%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

[module/date]
type = internal/date
interval = 5

date = %d/%m
date-alt = "%A, %d.%B %Y"

time = %H:%M
time-alt = %H:%M:%S

format-prefix = 
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #0a6cf5

label = %date% %time%

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume> <bar-volume>
label-volume = VOL %percentage%%
label-volume-foreground = ${root.foreground}

label-muted = 🔇 muted
label-muted-foreground = #666

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/alsa]
type = internal/alsa

format-volume = <label-volume> <bar-volume>
label-volume = VOL
label-volume-foreground = ${root.foreground}

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
label-muted = sound muted

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-underline = #ffb52a

format-discharging = <animation-discharging> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}

format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground-alt}
format-full-underline = ${self.format-charging-underline}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-foreground = ${colors.foreground-alt}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-foreground = ${colors.foreground-alt}
animation-charging-framerate = 750

animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-foreground = ${colors.foreground-alt}
animation-discharging-framerate = 750

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-underline = #f50a4d
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}

[module/powermenu]
type = custom/menu

expand-right = true

format-spacing = 1

label-open = 
label-open-foreground = ${colors.secondary}
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = systemctl reboot

menu-2-0 = power off
menu-2-0-exec = systemctl poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over

[global/wm]
margin-top = 5
margin-bottom = 0
```
My log:
```
polybar standard 
warn: No monitor specified, using "VGA-0"
warn: pulseaudio: using default sink alsa_output.pci-0000_00_14.2.analog-stereo
error: background_manager: Failed to copy slice of root pixmap (XCB_MATCH (8))

```
My Environment:

WM: i3
Output of `polybar -vvv`: 
```
polybar -vvv
polybar 3.3.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by Edhebi** [comment] 2019-01-05 21:48
exact same error using `arch` with `i3` and exact same `polybar -vvv` using a minimal config :

```dosini
[bar/master]
modules-center = date

[module/date]
type = internal/date
date = %A %d %B
```
Now, one weird thing is, when I run it inside a DM (mate here, also using i3 as a wm), I don't have that problem

**Comment by fliiiix** [comment] 2019-01-05 22:01
I see the same thing with i3 and my standard bar not showing up with the same issue. 
My config is here https://github.com/fliiiix/dotfiles/blob/master/config/configuration/polybar.tpl

Also sometimes it works so in 1/10 cases I see the bottom bar. But I wasn't able to figure out when and why it shows up some times.

**Comment by patrick96** [comment] 2019-01-07 21:01
Having this come up right now and from multiple people makes me think that this is a bug we introduced in the newest version.

@mamutal91 @Edhebi @ixolius Did you update polybar and now experience this? Or are you first time installers?

**Comment by ixolius** [comment] 2019-01-08 20:51
It happens since an update I made last Friday.

**Comment by patrick96** [comment] 2019-01-08 22:38
@ixolius Can you downgrade to polybar version 3.2.0 and see if the problem persists there. This would help us track down what changes introduced this bug. And if you know how to use `git bisect` it would help us out even more.

**Comment by Edhebi** [comment] 2019-01-09 01:18
broke spontaneously on an update

big new: no bug in 3.2.0, bug present in 3.3.0, and fixed in master :D

hope that help finding the culprit, I will have some time to check per-commit later

**Comment by patrick96** [comment] 2019-01-09 18:11
I am actually unable to reproduce this with either 3.3.0 or with the newest commit on arch with i3.

Could you all run polybar with `-l trace` and post the output of that here.

But interesting observation that this happens with and without the tray.

The part of the code that gives you this error was only added after 3.2.0 in #595. @bennofs seems like the pseudo-transparency changes aren't working as smooth for everyone as we thought.

**Comment by bennofs** [comment] 2019-01-09 18:47
I have a suspicion, it might be that we're now using the background manager even if a compositing manager is used (pseudo transparency not enabled) for the tray which I believe didn't happen before? Need to check

**Comment by bennofs** [comment] 2019-01-09 18:53
To those observing the problem, what compositing manager (if any) are you running (and with which options)?

**Comment by Edhebi** [comment] 2019-01-09 20:34
Not able to reproduce it anymore on 3.3.0 :/ (currently rebuilding my setup, so lotta program changing)

at the time of the report I wasn't using a background manager, nor a compositer, wich I do now (xcompmgr + pywal), and on my first post, the problem may have been coming from a weird state of DE setting the background, and i3 not understanding it ...

It's probably not helping much but hey, no issues anymore on my machine.

To everyone in this thread, do you still have problems with the master branch ? (git clone, follow compile instructions)

**Comment by bennofs** [comment] 2019-01-09 21:30
If anyone still has problems, please post a log with `-l trace` before changing anything that might "fix" the problem

**Comment by ixolius** [comment] 2019-01-11 11:50
@bennofs Here is my trace
```
 polybar -l trace standard
* Loading config: /home/ixolius/.config/polybar/config
- config: Copying missing params (sub="module/backlight-acpi", base="module/xbacklight")
- config: Current bar section: [bar/standard]
warn: No monitor specified, using "VGA-0"
* Loaded monitor VGA-0 (1920x1080+0+0)
* Bar geometry: 1920x35+0+0
- bar: Attach X event sink
- bar: Attach signal receiver
- controller: Install signal handler
- controller: Setup user-defined modules
- pulseaudio: started mainloop
warn: pulseaudio: using default sink alsa_output.pci-0000_00_14.2.analog-stereo
- module/powermenu: Creating menu level 0
- module/powermenu: Creating menu level item 0
- module/powermenu: Creating menu level item 1
- module/powermenu: Creating menu level 1
- module/powermenu: Creating menu level item 0
- module/powermenu: Creating menu level item 1
- module/powermenu: Creating menu level 2
- module/powermenu: Creating menu level item 0
- module/powermenu: Creating menu level item 1
* Starting application
- controller: Main thread id = 1
* Starting module/i3
* Starting module/xwindow
- module/i3: Thread id = 2
* Starting module/filesystem
- module/xwindow: Thread id = 3
* Starting module/pulseaudio
- module/filesystem: Thread id = 4
* Starting module/xkeyboard
* Starting module/memory
- module/xkeyboard: Thread id = 5
* Starting module/cpu
- module/memory: Thread id = 6
* Starting module/eth
* Starting module/date
* Starting module/powermenu
* Entering event loop (thread-id=1)
- module/cpu: Thread id = 7
- module/pulseaudio: Thread id = 8
- module/eth: Thread id = 9
* Eventqueue worker (thread-id=10)
- bar: Create renderer
- renderer: Get TrueColor visual
- renderer: Allocate colormap
- renderer: Allocate output window
- module/date: Thread id = 11
- renderer: Allocate window pixmaps
- renderer: Allocate graphic contexts
- renderer: Allocate alignment blocks
- renderer: Allocate cairo components
- module/powermenu: Thread id = 12
- background_manager: Finding root visual
- background_manager: Got root visual with depth 24
- background_manager: Allocating pixmap
- background_manager: Allocating graphics context
- background_manager: Allocating cairo surface
- background_manager: Fetching pixmap
error: background_manager: Failed to copy slice of root pixmap (XCB_WINDOW (3))
- renderer: Load fonts
* Configured DPI = 96x96
- background_manager: Finding root visual
- background_manager: Got root visual with depth 24
- background_manager: Allocating pixmap
- background_manager: Allocating graphics context
- background_manager: Allocating cairo surface
- background_manager: Fetching pixmap
error: background_manager: Failed to copy slice of root pixmap (XCB_WINDOW (3))
* Loaded font "fixed:pixelsize=10" (name=DejaVu Sans, offset=1, file=/usr/share/fonts/TTF/DejaVuSans.ttf)
* Loaded font "unifont:size=8:antialias=false" (name=Unifont, offset=0, file=/usr/share/fonts/misc/unifont.bdf)
* Loaded font "Wuncon Siji:style=Regular:pixelsize=10" (name=Wuncon Siji, offset=1, file=/usr/share/fonts/misc/siji.pcf)
- Activate root background manager
- background_manager: Finding root visual
- background_manager: Got root visual with depth 24
- background_manager: Allocating pixmap
- background_manager: Allocating graphics context
- background_manager: Allocating cairo surface
- background_manager: Fetching pixmap
- background_manager: Copying from root pixmap (18874618) 1x1+0x0
error: background_manager: Failed to copy slice of root pixmap (XCB_MATCH (8))
```
According to my `polybar -vvv`, I use a composite manager, but I don't know which. If you tell me how to find out, I will post it.

Sorry for the late reply, I cannot check this very often.

**Comment by patrick96** [comment] 2019-01-14 21:59
Interesting, @bennofs see how they got both `XCB_WINDOW (3)` and `XCB_MATCH (8)`.

The other curious thing is that when the error `XCB_MATCH (8)` occurs, the message `Copying from root pixmap` is printed, this means that the exception must be thrown in `copy_area_checked`, and indeed the manpages for `xcb_copy_area_checked` state:

```
       xcb_match_error_t
                 src_drawable has a different root or depth than dst_drawable.
```
But I can't figure out why this would actually occur.

When `XCB_WINDOW (3)` is the error, that line isn't printed, meaning that the error must occur before, the only calls to xcb before are

* `m_connection.translate_coordinates` this doesn't generate errors according to the manpages
* `m_connection.screen()` this was already called before in `allocate_resources` and so shouldn't throw any errors either
* `translated->dst_x` This is the only one left, so it must be the culprit. I think `translated` is still some form of cookie and its type has the `->` operator overloaded. But it's still strange because `translate_coordinates` isn't supposed to generate errors.

https://github.com/jaagr/polybar/blob/c3ef99b719307ca21683174dd361ef1c7367a038/src/x11/background_manager.cpp#L124-L140

**Comment by bennofs** [comment] 2019-01-14 22:54
https://tronche.com/gui/x/xlib/window-information/XTranslateCoordinates.html says that XTranslateCoordinates can throw BAD WINDOW so I would assume the xcb version can do so as well

**Comment by patrick96** [comment] 2019-01-15 17:19
@ixolius Was that output with `-l trace` with or without the tray enabled? Can you also post the output of `polybar -m` and `xrandr`. Does this happen when you don't start polybar in your i3 config?

@bennofs Seems like the xcb documentation is lying ;) 
So either `m_window` or `m_connection.screen()->root` or both are not defined windows. `m_window` is set to the window that the renderer created for polybar, so I don't see why that isn't a defined window. And also why wouldn't the root window be a defined window?

When it tries to copy a 1x1 slice, either
* `xcb_get_geometry` returned a 1x1 rect for the root pixmap (unlikely)
* `m_bar.outer_area(false)` gives us a 1x1 rect which would be caused by the bar width and height being set to 1x1

I hope the information ixolius can give us helps us here. Otherwise we will probably need to write a patch that adds much more logging and let ixolius apply it.

**Comment by ixolius** [comment] 2019-01-15 22:36
@bennofs afaik, I use ImageMagick for my wallpaper. I'm using the command `display -window root "$WALLPAPER"`, where `$WALLPAPER`contains path and filename.

**Comment by bennofs** [comment] 2019-01-15 23:09
@ixolius Thanks! With imagemagick I can finally reproduce this issue :+1:

**Comment by bennofs** [comment] 2019-01-16 08:38
The fix for this is mostly just a better error message. There appears to be no good way to get the background pixmap if the background-setting tool does not use the `ESETROOT_PMAP` property.

To anyone affected by this, I suggest using a different program the set the wallpaper. I usually test with `feh` (see `--bg-fill` and related) and `nitrogen`.

**Comment by bennofs** [comment] 2019-01-16 08:39
The fix for this is mostly just a better error message. There appears to be no good way to get the background pixmap if the background-setting tool does not use the `ESETROOT_PMAP` property.

To anyone affected by this, I suggest using a different program the set the wallpaper. I usually test with `feh` (see `--bg-fill` and related) and `nitrogen`. 

The PR above also fixes some cases where we tried to fetch the desktop wallpaper even though not necessary, so if you don't use pseudo-transparency this might also be enough.

**Closed** 2019-01-17 13:22 UTC
Labels: bug

**Comment by yngtodd** [comment] 2019-02-01 16:10
I just built from source on my Ubuntu machine and am getting the same error with `polybar example`.
