### ISSUE TITLE
Pcmanfm-qt not launching

### ISSUE THREAD

**Issue by GandaG** [jaagr/polybar#1414] opened 2018-09-04 22:37 UTC
## Describe the issue
The text module with `exec pcmanfm-qt &` for click-left does not open pcmanfm-qt when clicked.

**Expected behavior:**
A window of pcmanfm-qt open.

**Actual behavior:**
Nothing unfortunately.

## To Reproduce
```dosini
[bar/top]
modules-left = file-explorer

[module/file-explorer]
type = custom/text
content = "pcmanfm"
click-left = exec pcmanfm-qt &

```

## Polybar Log
```
* Loading config: /home/daniel/.config/polybar/config
- config: Current bar section: [bar/top]
warn: No monitor specified, using "eDP1"
* Loaded monitor eDP1 (1366x768+0+0)
* Bar geometry: 1366x24+0+0
- bar: Attach X event sink
- bar: Attach signal receiver
- controller: Install signal handler
- controller: Setup user-defined modules
* Starting application
- controller: Main thread id = 1
* Starting module/file-explorer
- module/file-explorer: Thread id = 2
* Entering event loop (thread-id=1)
* Eventqueue worker (thread-id=3)
- bar: Create renderer
- renderer: Get TrueColor visual
- renderer: Allocate colormap
- renderer: Allocate output window
- renderer: Allocate window pixmaps
- renderer: Allocate graphic contexts
- renderer: Allocate alignment blocks
- renderer: Allocate cairo components
- renderer: Load fonts
* Configured DPI = 96x96
warn: No fonts specified, using fallback font "fixed"
* Loaded font "fixed" (name=Linux Biolinum, offset=0, file=/usr/share/fonts/ttf-linux-libertine/LinBiolinum_Rah.ttf)
* Bar window: 0x1600002
- bar: Reconfigure window
- bar: Set window WM_NAME
- bar: Set window _NET_WM_WINDOW_TYPE
- bar: Set window _NET_WM_STATE
- bar: Set window _NET_WM_DESKTOP
- bar: Set window _NET_WM_PID
- bar: Map window
- bar: Draw empty bar
- bar: Setup tray manager
* Disabling tray manager (reason: missing `tray-position`)
* module/file-explorer: Rebuilding cache
- bar: Force update
* Redrawing bar window
- renderer: flush(1 geom=63x24+0+0, falloff=0)
- bar: Received expose event
- bar: Received expose event
- bar: Received button press: 1 at pos(46, 16)
- Found matching input area
* Uncaught input event, forwarding to shell... (input: exec pcmanfm-qt &)
* Executing shell command: exec pcmanfm-qt &
- command: Waiting for pid 2645 to finish...
- command: Exited with status 0
- bar: Force update
* Redrawing bar window
- renderer: flush(1 geom=63x24+0+0, falloff=0)
```

## Environment:
* WM: i3-gaps
* Output of `polybar -vvv`: 
```
polybar 3.2.1

Features: +alsa +curl +i3 +mpd +network +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context
Replacing `pcmanfm-qt` with either `qutebrowser` or `pcmanfm` works.

**Comment by TonCherAmi** [comment] 2018-09-04 23:12
What happens when you execute `pcmanfm-qt &` directly from your shell?

**Comment by GandaG** [comment] 2018-09-04 23:16
It just launches normally.

**Comment by TonCherAmi** [comment] 2018-09-04 23:51
Could you also try running `/bin/sh -c 'exec pcmanfm-qt &'`?

**Comment by GandaG** [comment] 2018-09-04 23:54
Exact same outcome. This is what's printed after I run either command:
```
qt5ct: using qt5ct plugin
isPrimaryInstance
qt5ct: D-Bus global menu: no
```
Not sure whether it's relevant though.

**Comment by TonCherAmi** [comment] 2018-09-05 00:15
Hmm, maybe try changing the command up a bit, try removing `exec` or `&` or both.

**Comment by TonCherAmi** [comment] 2018-09-05 01:25
Well, I am able to reproduce it, though I am not sure what's causing the issue. It might be not related to polybar at all, since there aren't any problems with other applications. You could try your luck asking `pcmanfm-qt` devs themselves.

**Comment by patrick96** [comment] 2018-09-11 16:10
Looks like a duplicate of #916. This bug has been on my TODO list for the longest time, should get cracking on this.

I have added a note in the [Known Issues page](https://github.com/jaagr/polybar/wiki/Known-Issues#click-commands-are-not-executed). tl;dr redirect all output from the command to `/dev/null` by appending `>/dev/null 2>&1` to the command (`&` still has to be at the end though).

**Closed by patrick96** 2018-09-11 16:10 UTC
Labels: duplicate
