### ISSUE TITLE
Failed to generate build

### ISSUE THREAD

**Issue by just12** [jaagr/polybar#825] opened 2017-10-30 19:31 UTC
I tried building from souce code but failed, no matter if i use the script or not. 
[CMakeError.log](https://github.com/jaagr/polybar/files/1428490/CMakeError.log)
[CMakeOutput.log](https://github.com/jaagr/polybar/files/1428491/CMakeOutput.log)

**Comment by patrick96** [comment] 2017-10-30 20:45
I don't think those log files tell us anything. Can you post the output of the `cmake` and the `command`

**Comment by Kokan** [comment] 2017-11-01 09:10
@just12 Do you have `pthread` installed ? In the attached file, it tries to find `pthread_create`, but cannot.

**Comment by just12** [comment] 2017-11-01 10:04
pthread is installed but it doesn't find pthread_create.
Here are the outputs of build.sh and cmake ..

[build.sh.txt](https://github.com/jaagr/polybar/files/1433744/build.sh.txt)
[cmake.txt](https://github.com/jaagr/polybar/files/1433745/cmake.txt)

**Comment by patrick96** [comment] 2017-11-01 10:30
When running the `build.sh`, you specified that you wanted to build with volume support, but your system doesn't have `alsalib` installed, that's why you get an error. If you run `cmake ..` and `make` inside a *clean* `build` directory, this shouldn't happen

**Comment by just12** [comment] 2017-11-01 10:57
Im doing this on a clean install and noticed that i din't have `alsa` installed, so i installed `alsa-base`. Isn't `alsalib` included in it?
Also, just for the sake of trying it, i removed the `build/` directory and tried to build only saying yes to `internal/i3` and `polybar/msg` and the same thing happens, it fails because it doesn't find `pthread_create`. 

[build.sh2.txt](https://github.com/jaagr/polybar/files/1433873/build.sh2.txt)

**Comment by patrick96** [comment] 2017-11-01 11:04
What distro are you using? Did you check the [Wiki](https://github.com/jaagr/polybar/wiki/Compiling) to make sure that you have all dependencies installed?

**Comment by just12** [comment] 2017-11-01 11:35
Im on lubuntu 17.04 zesty. I forgot to check the wiki, so i installed the dependencies listed and `cmake` was able to finish. Now the problem is with `make`.

[make.txt](https://github.com/jaagr/polybar/files/1433961/make.txt)

**Comment by patrick96** [comment] 2017-11-01 19:10
Now we're getting somewhere. Seems this is a duplicate of #644 
See the [next section](https://github.com/jaagr/polybar/wiki/Compiling#version-mismatch-between-xcb-proto-and-libxcb-randr0-dev) on the wiki for instructions on how to resolve this.

**Closed by patrick96** 2017-11-01 19:10 UTC
Labels: build
