### ISSUE TITLE
LTE network interface not displayed

### ISSUE THREAD

**Issue by l4ngl3y** [jaagr/polybar#351] opened 2017-01-17 19:33 UTC
Hello, I have USB LTE modem with interface enp0s26u1u2 if connected. My config file for it interface:

> modules-center = wired-network wireless-network lte-network vpn-network
...
> [module/lte-network]
> type = internal/network
> interface = enp0s26u1u2
> interval = 1
> format-connected = <label-connected>
> label-connected = LTE

But interface label not displayed. What am I doing wrong ???

**Comment by jaagr** [comment] 2017-01-17 19:46
Why are you setting `format-connected` to blank?

To show the LTE label you have to tell it to use it: `format-connected = <label-connected>`

**Comment by l4ngl3y** [comment] 2017-01-17 20:43
Ohh.... sorry .... github filtering tags...
my config:
[module/lte-network]
type = internal/network
interface = enp0s26u1u2
interval = 1
format-connected = <label-connected>
label-connected = LTE

**Comment by jaagr** [comment] 2017-01-17 20:57
OK, can you show the output of:

~~~ sh
$ ip link
~~~

**Comment by l4ngl3y** [comment] 2017-01-17 21:02
...
23: enp0s26u1u2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 1c:49:7b:58:85:9f brd ff:ff:ff:ff:ff:ff
...
Or all my link ? )

**Comment by jaagr** [comment] 2017-01-17 21:04
No that's fine.. Don't you get any error or warning messages from polybar?

**Comment by l4ngl3y** [comment] 2017-01-17 21:12
No.... I run polybar:
`~> polybar top -q -r -l info`
and not get any errors..... if i run polybar without `-l info`, I don't get too any errors...

**Comment by jaagr** [comment] 2017-01-17 21:19
Remove `-q` (see `polybar -h`)

It won't print warning messages

**Comment by l4ngl3y** [comment] 2017-01-17 21:26
Ohh... sorry....

> warn: The config parameter `bar/top.dock` is deprecated, use `override-redirect` instead.
> warn: The config parameter `bar/top.linecolor` is deprecated, use `{underline,overline}-color` instead.
> warn: The config parameter `bar/top.lineheight` is deprecated, use `{underline,overline}-size` instead.
> warn: Alpha support for the systray is limited. See the wiki for more details.
> warn: module/layout: The format tag <output> is deprecated, use <label> instead
> warn: module/date: The format tag `<date>` is deprecated, use `<label>` instead.
> warn: module/lte-network: Failed to query interface 'enp0s26u1u2'
> warn: module/lte-network: Failed to query interface 'enp0s26u1u2'
> warn: module/lte-network: Failed to query interface 'enp0s26u1u2'
> warn: module/lte-network: Failed to query interface 'enp0s26u1u2'
> warn: module/lte-network: Failed to query interface 'enp0s26u1u2'
> warn: module/lte-network: Failed to query interface 'enp0s26u1u2'
> warn: module/lte-network: Failed to query interface 'enp0s26u1u2'
> warn: module/lte-network: Failed to query interface 'enp0s26u1u2'
> warn: module/lte-network: Failed to query interface 'enp0s26u1u2'
> warn: module/lte-network: Failed to query interface 'enp0s26u1u2'
> warn: module/lte-network: Failed to query interface 'enp0s26u1u2'
> warn: module/lte-network: Failed to query interface 'enp0s26u1u2'
> warn: Termination signal received, shutting down...

**Comment by jaagr** [comment] 2017-01-17 21:53
OK, the query failed... this won't be fixed right now because I have started to refactor the network code to not use wireless_tools. You will have to wait until it's done.

**Comment by l4ngl3y** [comment] 2017-01-17 21:56
No problems... Thank you....

**Closed** 2017-01-23 16:56 UTC

**Comment by lockie** [comment] 2017-11-13 13:33
Hey, I was wondering if there's any approximate ETA set on that refactoring?
I'm having the same trouble as topic starter with USB CDC modem appearing as `usb0` ethernet interface, polybar just says "Failed to query interface 'usb0'". It would be lovely for polybar to support that sort of device.

**Comment by patrick96** [comment] 2018-05-15 12:30
I don't think the issue is `wireless_tools` but rather what was described in #1211, that `ethtool` doesn't fully support the usb network interface (try running `ethtool YOUR_IFACE_NAME`).

**Comment by ArcticXWolf** [comment] 2018-05-15 14:00
You can even use `ethtool -i YOUR_IFACE_NAME`, then ethtool shows you which parts your driver supports.

**Comment by patrick96** [comment] 2018-05-16 08:08
@ArcticXWolf I'm curious, what do you get when you run `ethtool -i` on your interface?

**Comment by AriaGrt** [comment] 2019-02-28 14:30
Any updates on the usb lan compatibility?

**Comment by patrick96** [comment] 2019-02-28 15:03
@AriaGrt: @ArcticXWolf wanted to open a PR for this (see #1211), but I don't think we ever received one
