### ISSUE TITLE
Module labels keep shifting entire bar - tokens not working properly?

### ISSUE THREAD

**Issue by TwelfthFace** [jaagr/polybar#841] opened 2017-11-13 14:37 UTC
Hi, i've just switched to polybar and i'm having trouble keeping my CPU and Memory module label text from changing width when the text changes as this causes the modules to the left of it move and it looks ugly.

[Example of problem IMGUR](https://imgur.com/a/70Adj)

Config
```
[colors]
background = #ee2f343f
background-alt = #f72f343f
foreground = #f3f4f5
foreground-alt = #f3f4f5
foreground-dim = #676e7d
primary = #ffb52a
secondary = #e60053
alert = #ff6600

high = #268bd2
high-alt = #0c2b41

[global/wm]
margin-top = 5
margin-bottom = 5

[bar/main]
;monitor = ${env:MONITOR:HDMI-1}
bottom = true
width = 100%
height = 40
offset-x = 0
offset-y = 0

;background = ${xrdb:color9}
background = ${colors.background}
foreground = ${colors.foreground}

overline-size = 2
overline-color = #f00
underline-size = 2
underline-color = ${colors.high}

spacing = 1
padding-left = 0
padding-right = 2
module-margin-left = 0
module-margin-right = 1

font-0 = System San Francisco Display:pixelsize=11;0
font-1 = FontAwesome:pixelsize=11;0



;font-0 = Roboto:pixelsize=16;0
;font-1 = FontAwesome:pixelsize=16;-2
;font-2 = unifont:size=6:heavy:fontformat=truetype;-2
;font-3 = siji:pixelsize=10;-4


modules-left = bspwm i3 xwindow
modules-center =
modules-right = mpd s mySpotify s volume s eth s memory cpu myLoad temperature s date
;systemRoot systemHome s

tray-position = right
tray-padding = 2
;tray-transparent = true
tray-background = ${colors.background}

;wm-restack = bspwm
;wm-restack = i3

;override-redirect = true

;scroll-up = bspwm-desknext
;scroll-down = bspwm-deskprev

;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev


[module/xwindow]
type = internal/xwindow
label = %title:0:45:...%
label-background = ${colors.background-alt}
label-padding = 2
format-underline = ${colors.high}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-underline = ${colors.secondary}
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}

label-layout = %layout%

label-indicator-padding = 2
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/bspwm]
type = internal/bspwm
ws-icon-default = x

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-occupied = %index%
label-occupied-padding = 2

label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true

label-mode = %mode%
label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline = ${colors.high}
label-focused-padding = 4

label-unfocused = %index%
label-unfocused-foreground = ${colors.foreground-dim}
label-unfocused-padding = 4

label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 4

label-visible = %index%
label-visible-foreground = ${module/bspwm.label-empty-padding}
label-visible-padding = ${module/bspwm.label-empty-padding}

[module/theme]
format-background = ${colors.background}
format-padding = 2
format-foreground = ${self.format-underline}

format-connected-background = ${module/theme.format-background}
format-unconnected-background = ${module/theme.format-background}
format-mounted-background = ${module/theme.format-background}
format-unmounted-background = ${module/theme.format-background}
format-charging-background = ${module/theme.format-background}
format-discharging-background = ${module/theme.format-background}

format-connected-padding = ${module/theme.format-padding}
format-unconnected-padding = ${module/theme.format-padding}
format-mounted-padding = ${module/theme.format-padding}
format-unmounted-padding = ${module/theme.format-padding}
format-charging-padding = ${module/theme.format-padding}
format-discharging-padding = ${module/theme.format-padding}

format-mounted-foreground = ${self.format-mounted-underline}
format-unmounted-foreground = ${self.format-unmounted-underline}

[module/mpd]
type = internal/mpd

inherit = module/theme

format-online = <toggle>   <label-song>    [ <label-time>  ]

label-song = %title% - %artist%
label-song-maxlen = 25
label-song-ellipsis = true

icon-prev = 
icon-seekb = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 
icon-seekf = 

icon-random = 
icon-repeat = 

;toggle-on-foreground = ${colors.primary}
;toggle-off-foreground = #66

;format-online-prefix = " "
format-online-underline = #20dfdf
format-online-background = #0d5959
format-online-padding = 4

[module/myBattery]
interval=1
type = custom/script
exec = /usr/lib/i3blocks/battery
format-underline = #ffb52a

[module/mySpotify]
inherit = module/theme
interval = 1
type = custom/script
exec = sh ~/spotify.sh
click-left = i3-msg workspace number 10
label = %output:0:30:...%
format-prefix = "  "
format-underline = #20dfdf
format-foreground = ${colors.foreground}
format-background = #0d5959

[module/volume]
type = internal/volume

format-volume = <label-volume> <bar-volume>
label-volume = "%{A3:pavucontrol&:}  %%{A}"
label-volume-foreground = ${root.foreground}
click-right = pavucontrol &

format-muted-prefix = "  "
format-muted-foreground = ${colors.foreground}
label-muted = "%{A3:pavucontrol&:}MUTED%{A}" 

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = true
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = "%{A3:pavucontrol&:}─%{A}"
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground}


[module/myVolume]
inherit = module/theme
interval = 0.5
type = custom/script
exec = /usr/lib/i3blocks/volume
scroll-up = pactl set-sink-volume 1 +1%
scroll-down = pactl set-sink-volume 1 -1%
click-left = urxvt -name float -e ncmpcpp &
click-right = pavucontrol &
format-prefix = ""
format-underline = #20dfdf

[module/myLoad]
inherit = module/theme
interval = 1
type = custom/script
exec = ~/.config/i3/scripts/load_average
click-left = urxvt -name float -e htop &
format-underline = #d33636

[module/systemRoot]
inherit = module/theme
type = internal/fs
interval = 20
mount-0 = /
label-mounted = " %free%"
label-unmounted = " ??"
format-mounted-underline = #39c639
format-unmounted-underline = #39c639

[module/systemHome]
inherit = module/theme
type = internal/fs
interval = 20
format-prefix = ""
mount-0 = /home
label-mounted = " %free%"
label-unmounted = " ??"
format-mounted-underline = #39c639
format-unmounted-underline = #39c639

[module/backlight]
type = internal/xbacklight

format = <label> <bar>
label = BL

bar-width = 10
bar-indicator = │
bar-indicator-foreground = #ff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}

[module/cpu]
inherit = module/theme
type = internal/cpu
interval = 2
format-padding = 2
#format-prefix = " "
format-underline = #d33636
label = %percentage:0:3%%

[module/memory]
inherit = module/theme
type = internal/memory
interval = 2
format-prefix = " "
format-underline = #999999
label = %percentage_used%

[module/wlan]
inherit = module/theme
type = internal/network
interface = wlo1
interval = 1

format-connected = <label-connected>
format-connected-underline = #268bd2
format-disconnected-underline = ${colors.alert}

;label-connected = " %local_ip% %signal% %downspeed% %upspeed%"
label-connected = " %signal% [  %downspeed% ] [  %upspeed% ]"
label-disconnected = "OFFLINE"
label-connected-foreground = ${colors.high}
label-disconnected-foreground = ${colors.alert}

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = ${colors.foreground-alt}

[module/eth]
inherit = module/theme
type = internal/network
interface = enp7s0
interval = 3.0

format-connected-underline = #55aa55
format-connected-prefix = " "
format-connected-foreground-foreground = ${colors.foreground-alt}
label-connected = %local_ip%

format-disconnected-underline = ${self.format-connected-underline}
label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${colors.foreground-alt}

[module/date]
inherit = module/theme
type = internal/date
interval = 1

time = "%a - %d.%m.%Y - %H:%M:%S"
time-alt = "%a - %d.%m.%Y - %I:%M %p"

format-prefix = " "
format-underline = ${colors.foreground}

label = %date% %time%

[module/battery]
inherit = module/theme
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 98

label-charging = " %percentage% [%time%]"
format-charging = <animation-charging> <label-charging>
format-charging-underline = #ffb52a

label-discharging = "%percentage% [%time%]"
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}

label-charging-foreground = ${self.format-charging-underline}
label-discharging-foreground = ${self.format-charging-underline}

format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground-alt}
format-full-underline = ${self.format-charging-underline}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${self.format-charging-underline}
ramp-capacity-0-foreground = ${colors.foreground}
ramp-capacity-0-background = ${colors.alert}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-foreground = ${self.format-charging-underline}
animation-charging-framerate = 750

[module/temperature]
inherit = module/theme
type = internal/temperature
thermal-zone = 0
warn-temperature = 65

format = <label>
format-underline = #d33636
format-warn = <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature%
label-warn = %temperature%
format-warn-foreground = ${colors.foreground}
format-warn-background = ${colors.alert}
format-warn-padding = ${self.format-padding}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}

[module/powermenu]
type = custom/menu

label-open =  power
label-open-foreground = ${colors.secondary}
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

; vim:ft=dosini

[module/s]
type = custom/text
content = " "
```
I've tried the tokens formatting (from wiki), see the [module/cpu] block, and that makes the module push right instead of left [see third image, note bottom left as the padding is being ignored](https://imgur.com/a/70Adj)

**Comment by NBonaparte** [comment] 2017-11-15 20:23
Use monospace fonts, as the shifts are caused by character widths not being equal. In the future we might be able to specify module widths or something similar that might mitigate this.

**Comment by patrick-motard** [comment] 2017-12-14 03:48
Funny, I'd run into the same issue and wondered if anyone else ran into it. Looks like they have. I use a monospaced font and have this issue. Consider the following:

```
[module/cpu]
type = internal/cpu
interval = 2
label = %percentage%%
```

In this example the bars width shifts by one character when CPU percentage goes above and below 9% (adding/removing a digit).

**Comment by NBonaparte** [comment] 2017-12-14 03:55
Does `label = %percentage:3%%` not work?

**Comment by patrick-motard** [comment] 2017-12-14 04:00
Aha! @NBonaparte you are a wizard! I'd completely missed that when reading over the formatting section of the readme! Worked like a charm.

**Comment by Divodurum** [comment] 2018-01-13 07:04
hello, I encounter exactly the same problem, but the token doesn't work...
To see if it changes something, I even tried`label = %percentage:10%%`: the block is then far more wider but keeps shifting when the value fluctuates between single and double digits.

To be sure, I also tried with the default config file/example bar which contains `label = %percentage:2%%` : it doesn't work neither...

**Comment by patrick96** [comment] 2018-01-13 20:10
@Divodurum is it possible that you use a non-monospaced font as well?

**Comment by Divodurum** [comment] 2018-01-14 02:19
You're right @patrick96 I tried with a monospaced font and it works !
I'm a little stupid haha, before I posted here, while looking for this probleme, I read several times about the monospaced font but I thought it didn't concern my case because my probleme was when the number of letters changed...
Anyway Thanks !

**Comment by patrick96** [comment] 2018-01-14 09:27
I think we can close this, as the original problem most likely was a non-monospaced font as well

**Closed by patrick96** 2018-01-14 09:27 UTC
