### ISSUE TITLE
Setting format to <label-mode> in the i3 module causes a segment fault

### ISSUE THREAD

**Issue by SpaceboyRoss01** [jaagr/polybar#1575] opened 2019-01-03 02:54 UTC
## Describe the issue
When using the i3 module and setting the format to `<label-mode>`, polybar segment faults.

**Expected behavior:**
Polybar to work.

**Actual behavior:**
Segment fault

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[module/i3]
type = internal/i3
format = <label-mode>
```

## Polybar Log
```
Segment fault (core dumped)
```

## Environment:
* WM: i3
* Output of `polybar -vvv`:  3.3.0

**Comment by patrick96** [comment] 2019-01-03 17:53
Duplicate of #975

**Comment by patrick96** [comment] 2019-01-03 17:53
See [this comment](https://github.com/jaagr/polybar/issues/975#issuecomment-389411648) for a workaround. The issue is that polybar expects `<label-state>` in `format` (that's a bug, it should actually be optional)

**Closed by patrick96** 2019-01-03 17:53 UTC
