### ISSUE TITLE
Polybar fails to build -Error 2

### ISSUE THREAD

**Issue by canopeerus** [jaagr/polybar#633] opened 2017-07-05 06:39 UTC
I'm on Fedora 26 and I'm trying to build polybar according to the instructions provided. I've grabbed all of the dependencies(pretty sure) and I get the following errors on sudo make install.

![2017-07-05-120442_1366x768_scrot](https://user-images.githubusercontent.com/23027755/27851975-af4f7914-614c-11e7-81dd-90ae5105ced2.png)

**Comment by patrick96** [comment] 2017-07-05 08:23
Hmm, the `implicit-fallthrough` seems to be on purpose here, no idea why it generated an error here.

Can you give me the output that was generated when you ran `cmake ..`

**Comment by AdityaVisvanathan** [comment] 2017-07-06 09:16
I got it to work. I was using a i3-gaps which I had compiled on my own but polybar needed the i3 package from  Fedora's repos. So I switched to i3 and polybar built and installed fine. The n I compiled i3-gaps and removed i3. Everything works now. Thanks a lot though.

**Comment by linuxunil** [comment] 2017-07-07 01:32
I'm also getting this error when building polybar on Fedora Rawhide.  I have all the dependencies installed and built i3-gaps from source.  Heres the output of [cmake ..](https://gist.github.com/linuxunil/a18614c0559e8f682d23acba10875c82)

**Comment by linuxunil** [comment] 2017-07-07 05:04
Found a solution by using clang to build instead of gcc.  Looks to be a duplicate of #572 which is where I found this solution.  I'm running gcc version 7.1.1

**Comment by patrick96** [comment] 2017-09-04 11:35
The GCC issue is tracked in #572

**Closed by patrick96** 2017-09-04 11:35 UTC
Labels: build

**Comment by patrick96** [comment] 2017-09-15 11:05
It seems that this error still occurs if jsoncpp has to be compiled from source, see #753.
