### ISSUE TITLE
Trouble building polybar on lubuntu

### ISSUE THREAD

**Issue by hallonfras** [jaagr/polybar#1423] opened 2018-09-16 15:17 UTC
## Build Process
*Describe how you build polybar, list the exact commands you are using:*
sudo ./build.sh

**If you build polybar directly from this repository:**

* Output of `git describe --tags`:

**If you use some other way (like the AUR):**

*List exactly where you are building from and which version you are building.*

## Build Log
*Post everything that is output to the terminal while building polybar below. This HAS to include the output of the `cmake` and `make` commands, if you used them.*
```
** Fetching submodules
** Removing existing build dir (-f)
** Setting build options
** Use GCC even if Clang is installed ----------------------------- [y/N]: 

** Include support for "internal/i3" (requires i3) ---------------- [y/N]: 

** Include support for "internal/alsa" (requires alsalib) --------- [y/N]: 

** Include support for "internal/pulseaudio" (requires libpulse) -- [y/N]: 

** Include support for "internal/network" (requires libnl/libiw) -- [y/N]: 

** Include support for "internal/mpd" (requires libmpdclient) ----- [y/N]: 

** Include support for "internal/github" (requires libcurl) ------- [y/N]: 

** Build "polybar-msg" used to send ipc messages ------------------ [y/N]: 

** Using compiler: g++/gcc
** Executing cmake command
-- Trying to enable ccache
-- Couldn't locate ccache, disabling ccache...
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type specified; using RelWithDebInfo
-- Using supported compiler GNU-7.3.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.15.10
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.13
-- Checking for module 'xcb-randr>=1.12'
--   Found xcb-randr, version 1.13
-- Checking for module 'xcb-xrm'
--   Found xcb-xrm, version 1.0
-- Checking for module 'xcb-cursor'
--   Found xcb-cursor, version 0.1.1
--  Build:
--    Type: RelWithDebInfo
--    CC: /usr/bin/gcc  -O2 -g -DNDEBUG
--    CXX: /usr/bin/g++  -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors -O2 -g -DNDEBUG
--    LD: /usr/bin/ld  
--  Targets:
-- [ ]   polybar-msg
-- [ ]   testsuite
--  Module support:
-- [ ]   alsa
-- [ ]   curl
-- [ ]   i3
-- [ ]   mpd
-- [ ]   network
-- [ ]   pulseaudio
-- [ ]   xkeyboard
--  X extensions:
-- [X]   xcb-randr (1.13)
-- [X]   xcb-randr (monitor support) (1.13)
-- [ ]   xcb-render
-- [ ]   xcb-damage
-- [ ]   xcb-sync
-- [ ]   xcb-composite
-- [ ]   xcb-xkb
-- [X]   xcb-xrm (1.0)
-- [X]   xcb-cursor (0.1.1)
--  Log options:
-- [X]   Trace logging
-- Font not found: fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.13
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.15", minimum required is "2.7") 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib/x86_64-linux-gnu/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib/x86_64-linux-gnu/libxcb-ewmh.so  
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib/x86_64-linux-gnu/libxcb-util.so  
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Searching for xcbgen with python2
-- Found xcbgen in /usr/lib/python2.7/dist-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xproto.xml
-- Configuring done
-- Generating done
-- Build files have been written to: /home/isaac/.apps/polybar/build
** Building project
Scanning dependencies of target xpp
[  1%] Linking CXX static library libxpp.a
[  4%] Built target xpp
Scanning dependencies of target polybar
[  5%] Building CXX object bin/CMakeFiles/polybar.dir/cairo/utils.cpp.o
[  7%] Building CXX object bin/CMakeFiles/polybar.dir/components/bar.cpp.o
[  8%] Building CXX object bin/CMakeFiles/polybar.dir/components/builder.cpp.o
[ 10%] Building CXX object bin/CMakeFiles/polybar.dir/components/command_line.cpp.o
[ 11%] Building CXX object bin/CMakeFiles/polybar.dir/components/config.cpp.o
[ 13%] Building CXX object bin/CMakeFiles/polybar.dir/components/controller.cpp.o
[ 14%] Building CXX object bin/CMakeFiles/polybar.dir/components/ipc.cpp.o
[ 16%] Building CXX object bin/CMakeFiles/polybar.dir/components/logger.cpp.o
[ 17%] Building CXX object bin/CMakeFiles/polybar.dir/components/parser.cpp.o
[ 19%] Building CXX object bin/CMakeFiles/polybar.dir/components/renderer.cpp.o
[ 20%] Building CXX object bin/CMakeFiles/polybar.dir/components/screen.cpp.o
[ 22%] Building CXX object bin/CMakeFiles/polybar.dir/components/taskqueue.cpp.o
[ 23%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/animation.cpp.o
[ 25%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/iconset.cpp.o
[ 26%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/label.cpp.o
[ 28%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/progressbar.cpp.o
[ 29%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/ramp.cpp.o
[ 31%] Building CXX object bin/CMakeFiles/polybar.dir/events/signal_emitter.cpp.o
[ 32%] Building CXX object bin/CMakeFiles/polybar.dir/events/signal_receiver.cpp.o
[ 34%] Building CXX object bin/CMakeFiles/polybar.dir/main.cpp.o
[ 35%] Building CXX object bin/CMakeFiles/polybar.dir/modules/backlight.cpp.o
[ 37%] Building CXX object bin/CMakeFiles/polybar.dir/modules/battery.cpp.o
[ 38%] Building CXX object bin/CMakeFiles/polybar.dir/modules/bspwm.cpp.o
[ 40%] Building CXX object bin/CMakeFiles/polybar.dir/modules/counter.cpp.o
[ 41%] Building CXX object bin/CMakeFiles/polybar.dir/modules/cpu.cpp.o
[ 43%] Building CXX object bin/CMakeFiles/polybar.dir/modules/date.cpp.o
[ 44%] Building CXX object bin/CMakeFiles/polybar.dir/modules/fs.cpp.o
[ 46%] Building CXX object bin/CMakeFiles/polybar.dir/modules/ipc.cpp.o
[ 47%] Building CXX object bin/CMakeFiles/polybar.dir/modules/memory.cpp.o
[ 49%] Building CXX object bin/CMakeFiles/polybar.dir/modules/menu.cpp.o
[ 50%] Building CXX object bin/CMakeFiles/polybar.dir/modules/meta/base.cpp.o
[ 52%] Building CXX object bin/CMakeFiles/polybar.dir/modules/script.cpp.o
[ 53%] Building CXX object bin/CMakeFiles/polybar.dir/modules/systray.cpp.o
[ 55%] Building CXX object bin/CMakeFiles/polybar.dir/modules/temperature.cpp.o
[ 56%] Building CXX object bin/CMakeFiles/polybar.dir/modules/text.cpp.o
[ 58%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xbacklight.cpp.o
[ 59%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xwindow.cpp.o
[ 61%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xworkspaces.cpp.o
[ 62%] Building CXX object bin/CMakeFiles/polybar.dir/utils/bspwm.cpp.o
[ 64%] Building CXX object bin/CMakeFiles/polybar.dir/utils/command.cpp.o
[ 65%] Building CXX object bin/CMakeFiles/polybar.dir/utils/concurrency.cpp.o
[ 67%] Building CXX object bin/CMakeFiles/polybar.dir/utils/env.cpp.o
[ 68%] Building CXX object bin/CMakeFiles/polybar.dir/utils/factory.cpp.o
[ 70%] Building CXX object bin/CMakeFiles/polybar.dir/utils/file.cpp.o
[ 71%] Building CXX object bin/CMakeFiles/polybar.dir/utils/inotify.cpp.o
[ 73%] Building CXX object bin/CMakeFiles/polybar.dir/utils/io.cpp.o
[ 74%] Building CXX object bin/CMakeFiles/polybar.dir/utils/process.cpp.o
[ 76%] Building CXX object bin/CMakeFiles/polybar.dir/utils/socket.cpp.o
[ 77%] Building CXX object bin/CMakeFiles/polybar.dir/utils/string.cpp.o
[ 79%] Building CXX object bin/CMakeFiles/polybar.dir/utils/throttle.cpp.o
[ 80%] Building CXX object bin/CMakeFiles/polybar.dir/x11/atoms.cpp.o
[ 82%] Building CXX object bin/CMakeFiles/polybar.dir/x11/connection.cpp.o
[ 83%] Building CXX object bin/CMakeFiles/polybar.dir/x11/cursor.cpp.o
In file included from /home/isaac/.apps/polybar/src/x11/cursor.cpp:1:0:
/home/isaac/.apps/polybar/include/x11/cursor.hpp:18:16: error: ‘map’ does not name a type; did you mean ‘pixmap’?
   static const map<string, vector<string>> cursors = {
                ^~~
                pixmap
In file included from /home/isaac/.apps/polybar/src/x11/cursor.cpp:1:0:
/home/isaac/.apps/polybar/include/x11/cursor.hpp:22:4: error: extra ‘;’ [-Wpedantic]
   };
    ^
/home/isaac/.apps/polybar/src/x11/cursor.cpp: In function ‘bool polybar::v3_2_1::cursor_util::valid(std::__cxx11::string)’:
/home/isaac/.apps/polybar/src/x11/cursor.cpp:7:9: error: ‘cursors’ was not declared in this scope
     if (cursors.find(name) != cursors.end())
         ^~~~~~~
/home/isaac/.apps/polybar/src/x11/cursor.cpp:7:9: note: suggested alternative: ‘cursor’
     if (cursors.find(name) != cursors.end())
         ^~~~~~~
         cursor
/home/isaac/.apps/polybar/src/x11/cursor.cpp: In function ‘bool polybar::v3_2_1::cursor_util::set_cursor(xcb_connection_t*, xcb_screen_t*, xcb_window_t, std::__cxx11::string)’:
/home/isaac/.apps/polybar/src/x11/cursor.cpp:19:31: error: ‘cursors’ was not declared in this scope
     for (auto&& cursor_name : cursors.at(name)) {
                               ^~~~~~~
/home/isaac/.apps/polybar/src/x11/cursor.cpp:19:31: note: suggested alternative: ‘cursor’
     for (auto&& cursor_name : cursors.at(name)) {
                               ^~~~~~~
                               cursor
bin/CMakeFiles/polybar.dir/build.make:1310: recipe for target 'bin/CMakeFiles/polybar.dir/x11/cursor.cpp.o' failed
make[2]: *** [bin/CMakeFiles/polybar.dir/x11/cursor.cpp.o] Error 1
CMakeFiles/Makefile2:472: recipe for target 'bin/CMakeFiles/polybar.dir/all' failed
make[1]: *** [bin/CMakeFiles/polybar.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
** Failed to build project

```

## Environment:
* Distro (with Version):
Lubuntu 18.04

## Additional context
*Add any other context that you think is necessary about the problem here.*
Thanks in advance

**Comment by TonCherAmi** [comment] 2018-09-16 15:27
Looks like a duplicate of #1408, try building from latest master.

**Comment by patrick96** [comment] 2018-09-16 19:15
Installing `libxcb-xkb-dev` should also fix this.

**Closed by patrick96** 2018-09-16 19:15 UTC
Labels: duplicate
