### ISSUE TITLE
inline color definition by reference

### ISSUE THREAD

**Issue by ecly** [jaagr/polybar#771] opened 2017-09-23 08:33 UTC
Is there any way to define an inline color for eg. foreground by using a reference.
I seem to be unable to get it to work and can't find an example of this specific case in the wiki.

My expectation was that the following would work:
```
[colors]
foreground-alt =  ${xrdb:color2:#555}
...
ws-icon-0 = "1;%{F${colors.foreground-alt}}%{F-} web"
```

This however results in no coloring and output "} web".

**Comment by patrick96** [comment] 2017-09-23 08:42
This is a duplicate of #615 

The only way to achieve this right now is by using an environment variable to set the value for `ws-icon-0`:
```dosini
ws-icon-0 = ${env:WS_ICON_0}
```
And in some script that is sourced before polybar is started:
```bash
exprt WS_ICON_0="1;%{F${COLOR_FG_ALT}}%{F-} web"
```
You'll also need to define all the colors as shell variables

**Closed by patrick96** 2017-09-23 08:42 UTC
Labels: duplicate

**Comment by ecly** [comment] 2017-09-23 08:47
@patrick96 - sorry, I missed it! Thanks a lot!

**Comment by patrick96** [comment] 2017-09-23 09:00
No worries. I've added a section to the wiki formatting page to address this.

**Comment by ecly** [comment] 2017-09-23 10:01
As a note, I've found that that %{F} gets overriden by the related foreground definition in this context.

Eg. if I for this case define the following colors foregrounds:
```
label-visible-foreground = ${colors.foreground-alt}
label-focused-foreground = ${colors.highlight}
label-unfocused-foreground = ${colors.foreground-alt}
label-urgent-foreground = ${colors.foreground-alt}
```

Then the relevant one will be applied only to my icon if I merely do this:
```
ws-icon-0 = "1;%{F}%{F-} web"
```

This actually happened to allow me to do `almost` exactly what I wanted.
Don't know if that will prove useful for anyone, but thought I'd tag that along.

**Comment by patrick96** [comment] 2017-09-23 11:10
Are you using the latest polybar built from git? If so then this behaviour is not intended, by default if just `%{F}` is specified, the bar foreground color should be used. It seems this is just a side effect of #639.

**Comment by ecly** [comment] 2017-09-23 11:13
I should be.

```
$ polybar --version
polybar 3.0.5-26-g2d1e3c2
```

This behavior is able to easily give me close to what I want, but does not allow me to get exactly what I want using the method you described in the wiki.

**Comment by patrick96** [comment] 2017-09-23 11:29
How are you not able to get the behaviour you want with the method I described here and in the wiki?

**Comment by ecly** [comment] 2017-09-23 11:48
Wooops! I must've just made a mistake the first time around trying to apply that method. Went to verify that I wasn't saying anything terrible misguided, and I got it working the second time around. Cheers!

**Comment by patrick96** [comment] 2017-09-23 11:52
Great!
