### ISSUE TITLE
System tray icon removal shrinks adjacent text

### ISSUE THREAD

**Issue by rudevdr** [jaagr/polybar#1035] opened 2018-02-17 07:26 UTC
When I open certain application which provide system tray icon for e.g slack, it looks like this:
 
![2018-02-16-212246_1366x768_scrot](https://user-images.githubusercontent.com/19689713/36338965-07b43bc0-13e1-11e8-80b4-012add594bcc.png)

But when the application is closed and the system tray is removed the clock shrinks like this: 

![2018-02-16-212300_1366x768_scrot](https://user-images.githubusercontent.com/19689713/36338981-2c758c70-13e1-11e8-81ca-b9e987c5546f.png)

In my config, in the bar module I have two only configs for tray:

`tray-position = right`
`tray-padding = 2`.

The bar looks normal when i3 config is refreshed.

The bar behaves similar after system tray removal of qbittorrent icon.

**Comment by patrick96** [comment] 2018-02-17 14:39
Duplicate of #591

**Closed by patrick96** 2018-02-17 14:39 UTC
Labels: tray
