### ISSUE TITLE
Polybar no longer print font awesome

### ISSUE THREAD

**Issue by eoli3n** [jaagr/polybar#941] opened 2018-01-06 13:52 UTC
Hi,
From ``ttf-font-awesome-4.7.0-5-any.pkg.tar.xz`` to ``ttf-font-awesome-5.0.2-1-any.pkg.tar.xz`` on Archlinux breaks polybar which doesn't display font anymore.

Last polybar-git version.

In ``.config/polybar/config``
```
font-3 = FontAwesome:pixelsize=14;2
```
When launching
```
warn: Dropping unmatched character  (U+f0ac)
warn: Dropping unmatched character  (U+f054)
warn: Dropping unmatched character  (U+f185)
warn: Dropping unmatched character  (U+f028)
warn: Dropping unmatched character  (U+f021)
warn: Dropping unmatched character  (U+f0ec)
warn: Dropping unmatched character  (U+f1eb)
warn: Dropping unmatched character  (U+f240)
```
As https://github.com/jaagr/polybar/issues/392 , tried to update font cache, didn't work.

FROM

![alt tag](https://github.com/eoli3n/dotfiles/blob/master/screenshots/i3gaps.png)

TO 

![alt tag](https://ptpb.pw/vW_k.png)

**Comment by patrick96** [comment] 2018-01-06 13:55
duplicate of #924 
TL;DR you'll need to update your font specifiers and also possibly some of your icons, since FA5 may use other icon codes

**Closed by patrick96** 2018-01-06 13:55 UTC

**Comment by eoli3n** [comment] 2018-01-06 14:31
Oh, sorry, didn't search ... aur ttf-font-awesome-4 fixed it
