### ISSUE TITLE
libharfbuzz: Undefined reference to 'FT_Get_Var_Blend_Coordinates'

### ISSUE THREAD

**Issue by taylorthurlow** [jaagr/polybar#310] opened 2017-01-08 21:48 UTC
Getting this error on both my desktop and laptop. Using `polybar` or `polybar-git` package from AUR has the same issue. Both on `4.4.40-1-lts` kernel.

    [100%] Linking CXX executable polybar
    /usr/lib/libharfbuzz.so.0: undefined reference to 'FT_Get_Var_Blend_Coordinates'
    collect2: error: ld returned 1 exit status
    make[2]: *** [bin/CMakeFiles/polybar.dir/build.make:2138: bin/polybar] Error 1
    make[1]: *** [CMakeFiles/Makefile2:334: bin/CMakeFiles/polybar.dir/all] Error2
    make: *** [Makefile:128: all] Error 2

I'll see if I can figure out how to try older builds, still getting used to Linux as a daily driver.

**Comment by NBonaparte** [comment] 2017-01-08 21:57
Seems to be a harfbuzz issue caused by the latest update. Some guys have figure out a workaround: https://www.reddit.com/r/archlinux/comments/5mphpu/psa_harfbuzz_update_infinality_breaking_system/

**Comment by taylorthurlow** [comment] 2017-01-08 22:12
Thanks @NBonaparte, works great now. Here's hoping this apparently new `freetype2` interpreter version 40 will look close to infinality.

**Comment by jaagr** [comment] 2017-01-08 22:14
Good find @NBonaparte.. We should maybe leave this open for a while to avoid duplicates

**Comment by taylorthurlow** [comment] 2017-01-08 22:20
If anyone is curious what I did to fix it, I removed `infinality` entirely, supposedly the newest interpreter for `freetype2` works just as well.

- First remove `infinality` with: `sudo pacman -S --asdeps freetype2 cairo fontconfig`

- Edit `/etc/pacman.conf` (or wherever you happen to have your `pacman` config if you changed it) and remove the additional `infinality-bundle` repositories

- Run `sudo pacman -Syyu` and watch the output to make sure it's not looking for and updating the `infinality-bundle` repositories anymore.

That should do it and everything should compile fine, but I also switched my `freetype2` interpreter by editing `/etc/profile.d/freetype2.sh` and uncommenting the last line, making sure it reads: `truetype:interpreter-version=40`

Restart and you should be all good.

**Comment by gcarq** [comment] 2017-01-09 17:47
harfbuzz needs a rebuild, until this is fixed you can force a build with ABS:

```
$ abs extra/harfbuzz
$ cp -r /var/abs/extra/harfbuzz /tmp
$ # increase patch version in PKGBUILD
$ cd /tmp/harfbuzz
$ makepkg -si
 ```

You don't need to remove infinality

**Comment by zuzukrukov** [comment] 2017-01-10 08:32
Thanks @gcarq. Works for me.

**Comment by Fopedush** [comment] 2017-01-13 18:37
Thanks also,  @gcarq. The procedure he outlined worked for me, but I also had to reinstall gdk-pixbuf2 afterwards.

**Comment by bimmlerd** [comment] 2017-01-29 13:28
Removing infinality is probably a good idea, as it is dead. For those of you following @taylorthurlow's instructions, also consider `sudo pacman -S --asdeps jdk8-openjdk` if you had the infinality version of the JDK installed.

**Comment by mimoralea** [comment] 2017-02-03 17:27
I tried both and it was @taylorthurlow's the one that worked. Also remember to reinstall `gdk-pixbuf2` as @Fopedush mentions.

My point, try both. Your milage may vary.

**Comment by mimoralea** [comment] 2017-03-29 00:09
Another good way to solve this problem is to install the `downgrade` tool and downgrade the version of `harfbuzz`.

```
sudo pacman -S downgrade
sudo downgrade harfbuzz # select version 1.3.4

```

**Comment by fabrixx** [comment] 2017-08-01 18:47
Thank you  mimoralea you saved me!!

**Comment by patrick96** [comment] 2017-09-04 12:13
I think we can close this. Infinality has been dead for some time and no one should be using it

**Closed by patrick96** 2017-09-04 12:13 UTC
