### ISSUE TITLE
Alsa audio module muting bot the Master and Speaker channels..

### ISSUE THREAD

**Issue by mfoncho** [jaagr/polybar#1176] opened 2018-04-18 00:16 UTC
Pulseaudio module mutes both the alsa-audio Master and Speaker channels when i click on the icon. On clicking on it the second time it unmutes the Master but not the Speaker channel still inhibiting sound. Is there a way to disable the click handlers on the a pulseaudio module as i encounterd this when i mistakenly click on the volume module status

**Comment by NBonaparte** [comment] 2018-04-18 02:06
Pulseaudio doesn't have channels, are you referring to alsa channels?

**Comment by mfoncho** [comment] 2018-04-18 04:50
@NBonaparte yes i'm refering to the alsa channels. I was able rebuild the it without the scroll and right click and scroll listeners

**Comment by mfoncho** [comment] 2018-04-18 05:47
I refered to it as pulse audio because the modules is called pulseaudio in the source code even though its just an object wrapper interfaing with the alsa api

**Comment by mfoncho** [comment] 2018-04-18 07:27
```
[module/volume]
type=internal/volume
```

**Comment by patrick96** [comment] 2018-04-18 07:33
That's the alsa module. If your system uses pulseaudio, use the [pulseaudio](https://github.com/jaagr/polybar/wiki/Module:-pulseaudio) module (you will need to use the `polybar-git` package). If not, we'll have to debug this further, as I haven't seen this problem when only alsa is used,

**Comment by mfoncho** [comment] 2018-04-18 08:48
@patrick96 i dont understand.. from the source its clear alsa is the underlying implementation. I built the polybar from source because i had to make some changes from the wireless_tool to nl80211. The system is a lenovo T530 with alsa drivers and a pulseaudio server.

**Comment by patrick96** [comment] 2018-04-18 08:51
It's not, the pulseaudio interacts with the pulseaudio library (libpulse). I don't know where you see the pulseaudio module use the alsa API

**Comment by mfoncho** [comment] 2018-04-18 08:57
@patrick96 i used the alsa api. 
i have tried
```
type = internal/alsa
```
and 
```
type=internal/volume
```
So what i'm saying is this is a bug in the polybar alsa module.

**Comment by mfoncho** [comment] 2018-04-18 09:01
Both configurations lead to the same bug I can rename the the topic to Alsa.

**Comment by patrick96** [comment] 2018-04-18 09:05
internal/volume is just the old (deprecated) name for internal/alsa, their functionality is identical. The problem you have is not a polybar one, but caused by using alsa controls when you use both alsa and pulse, this was already reported in #900, #505, #704 and [here](https://bugs.launchpad.net/ubuntu/+source/pulseaudio/+bug/878986). That's why I suggested using the pulseaudio module because it doesn't have this problem.
Closing this as a duplicate.

**Closed by patrick96** 2018-04-18 09:05 UTC
Labels: duplicate

**Comment by mfoncho** [comment] 2018-04-18 09:11
@patrick96 i have both the pulseaudio server and alsa driver installed on my system so what configutation should i use for my current build?

**Comment by patrick96** [comment] 2018-04-18 09:13
[This](https://github.com/jaagr/polybar/wiki/Module:-pulseaudio)

**Comment by mfoncho** [comment] 2018-04-18 10:07
rebuilt my moded version with alsa and broke and bar.
but a fresh clone from github with ```type=internal/pulseaudio``` worked as expected
