### ISSUE TITLE
sudo make userconfig: file INSTALL cannot find "/home/emil/polybar/doc/config".

### ISSUE THREAD

**Issue by emme1444** [jaagr/polybar#1747] opened 2019-04-19 19:38 UTC
## Build Process
I used this to build on Ubuntu 18.04.2:
```
$ cd
$ git clone --recursive https://github.com/jaagr/polybar
$ mkdir polybar/build
$ cd polybar/build
$ cmake ..
$ make -j$(nproc)
$ sudo make install
$ sudo make userconfig
```

However the build process, described above, fails on the last command. This is a dump:
```
[  4%] Built target jsoncpp_lib_static
[ 10%] Built target xpp
[ 12%] Built target i3ipc++
[ 97%] Built target poly
[100%] Built target polybar
CMake Error at cmake/userconfig.cmake:7 (file):
  file INSTALL cannot find "/home/emil/polybar/doc/config".


CMakeFiles/userconfig.dir/build.make:57: recipe for target 'CMakeFiles/userconfig' failed
make[3]: *** [CMakeFiles/userconfig] Error 1
CMakeFiles/Makefile2:131: recipe for target 'CMakeFiles/userconfig.dir/all' failed
make[2]: *** [CMakeFiles/userconfig.dir/all] Error 2
CMakeFiles/Makefile2:138: recipe for target 'CMakeFiles/userconfig.dir/rule' failed
make[1]: *** [CMakeFiles/userconfig.dir/rule] Error 2
Makefile:190: recipe for target 'userconfig' failed
make: *** [userconfig] Error 2
```

I've checked; `/home/emil/polybar/doc/config`. It doesn't exist. 

Running the command:
```
$ sudo install -Dm644 /usr/share/doc/polybar/config $HOME/.config/polybar/config
```
does not work either and produces this error:
```
install: cannot stat '/usr/share/doc/polybar/config': No such file or directory
```
I've checked; `/usr/share/doc/polybar/config`. It doesn't exist either.

I have no idea how to get the default config file and why it isn't in any of the paths. It is nowhere to be found in any documentation, nor has anyone else had this problem on the internet. Of what I could find, at least. 

## Environment:
* Ubuntu (18.04.2 LTS):

Thanks for reading this! I guess!

**Comment by Lomadriel** [comment] 2019-04-19 19:55
If the install directory isn't specified the config should be in `/usr/local/share/doc/polybar/`.
`sudo make userconfig` install the config in the root directory. You should run `make userconfig` to install the config in your home.

**Comment by patrick96** [comment] 2019-04-19 20:13
This is basically a duplicate of  #1733 which is caused by not including the `doc` directory when sphinx is not installed.

To resolve this, either grab the [release tar ball](https://github.com/jaagr/polybar/releases/tag/3.3.1) and build from that or install `python3-sphinx` and remove the `build` directory and rebuild.

**Closed by patrick96** 2019-04-19 20:13 UTC

**Comment by Lomadriel** [comment] 2019-04-19 20:19
Ah okay, I totally forgot that sorry :/

**Comment by emme1444** [comment] 2019-04-19 20:59
Wait!
I used:
```
$ sudo apt-get install python3-sphinx
```
But I get an error when running the `build.sh` script: 
```
Scanning dependencies of target doc_html
[  1%] sphinx-build html: see doc/builder-html.log
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 14, in <module>
    from sphinx import main
ImportError: cannot import name 'main'
doc/CMakeFiles/doc_html.dir/build.make:57: recipe for target 'doc/CMakeFiles/doc_html' failed
make[2]: *** [doc/CMakeFiles/doc_html] Error 1
CMakeFiles/Makefile2:343: recipe for target 'doc/CMakeFiles/doc_html.dir/all' failed
make[1]: *** [doc/CMakeFiles/doc_html.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
** Failed to build project
```

Basically, using the python intepreter, I can `import sphinx`, it comes back with no errors. But when I try calling `from sphinx import main` it fails. 

I am really tired right now! 
Any help would be very appreciated. 
Thanks in advance!
