### ISSUE TITLE
Allow breaking the output into two lines.

### ISSUE THREAD

**Issue by lebarondemerde** [jaagr/polybar#1365] opened 2018-08-07 16:15 UTC
Hi.

Please, consider implementing the ability to break the output of ( some ) modules into two lines, like this:

![monitor-system-usage-stats-your-mac-os-x-menu-bar 1280x600](https://user-images.githubusercontent.com/20615335/43788480-04de361e-9a5d-11e8-903b-1a1cb0702b14.jpg)

Thanks!

**Comment by NBonaparte** [comment] 2018-08-08 04:41
Duplicate of #1363.

**Closed by NBonaparte** 2018-08-08 04:41 UTC
