### ISSUE TITLE
Tray icons draw above non-fullscreen windows

### ISSUE THREAD

**Issue by 132ikl** [jaagr/polybar#1375] opened 2018-08-12 02:35 UTC
When you have a window that covers your bar, including your tray, the entire bar will render below the window, excluding the bar. This is especially apparent in windowed fullscreen windows (ie windows that aren't fullscreen, but are the same size as your monitor.

Windowed Fullscreen OpenGL Game:
![image](https://user-images.githubusercontent.com/8751613/43997893-b95efd60-9db6-11e8-8737-5c112c1e45e6.png)

Transparent terminal running pipes.sh
![image](https://user-images.githubusercontent.com/8751613/43997897-cd78a468-9db6-11e8-9d75-523dcaa17080.png)

**Comment by NBonaparte** [comment] 2018-08-12 02:54
Duplicate of #425.

**Closed by NBonaparte** 2018-08-12 02:54 UTC
