### ISSUE TITLE
Failing to get unicode through

### ISSUE THREAD

**Issue by quite** [jaagr/polybar#251] opened 2016-12-18 10:56 UTC
I prefer to not use specialized so called icon fonts, but rather real Unicode points. I'm mostly using the Terminus font, but while testing this I've tried all sort. Both fontconfig and XLFD. Typically I can get through the `→` but not `✉` and others. The latter showing up either as not at all, or as various inverted question-marks and such. This is from latest git, sure. Any clues?

**Comment by jaagr** [comment] 2016-12-20 04:10
Are you loading a font with support for the glyphs?

**Comment by quite** [comment] 2016-12-20 08:22
Yeah, I can see `✉` in urxvt using Terminus font. That's my litmus test for now.

**Comment by jaagr** [comment] 2016-12-20 10:51
Verify that the same font gets loaded: 
~~~
$ fc-match -v '<font-pattern-defined-in-your-polybar-config-pre-semicolor>'
~~~

**Comment by quite** [comment] 2016-12-20 11:40
I did that. Also tried with and without fontformat=truetype. I guess I'd
have to test with a very clean polybar config etc, when I'm able to and have
time...

**Comment by jaagr** [comment] 2016-12-20 13:56
are you maybe using 4+ byte sequences?

**Comment by guilhermefelipecgs** [comment] 2016-12-31 19:02
@jaagr I think that's the problem, all unicodes characters with more than 4 bytes doesn't work for me too.

**Comment by jaagr** [comment] 2017-01-01 00:00
@guilhermefelipecgs yeah it's currently not supported.. been planning on replacing the font rendering to get rid of xft.. it's unlikely to be fixed until then

**Comment by jaagr** [comment] 2017-01-01 02:25
@quite ✉ works fine for me

**Comment by guilhermefelipecgs** [comment] 2017-01-01 12:42
@quite here works too, I think the problem is your font, try dejavu sans mono, that font has the ✉

**Comment by jaagr** [comment] 2017-01-09 14:50
Closing as 4+ byte unicode glyphs aren't supported and won't be with the current font handling.

**Closed by jaagr** 2017-01-09 14:50 UTC
