### ISSUE TITLE
Choose time zone

### ISSUE THREAD

**Issue by M1dgard** [jaagr/polybar#1238] opened 2018-05-16 11:26 UTC
AFAICS `internal/date` can't be configured to show a fixed time zone.

Multiple clocks showing different time zones are useful for people who are often abroad (to show their home time next to the local time), and for people who work together with people in other time zones.

The same effect can be achieved by using the script module running `date`, but this seems like something that would be nice to have in the internal module.

**Comment by patrick96** [comment] 2018-05-16 11:36
Duplicate of #596.

There was a PR for this (#788) but the author seems to have gone and also the approach added a new dependency. This is still on our TODO list though

**Closed by patrick96** 2018-05-16 11:36 UTC
Labels: duplicate

**Comment by M1dgard** [comment] 2018-05-16 11:43
Oops, sorry for the dup. I searched the code but forgot to search the issues this time.
