### ISSUE TITLE
unrecognized token

### ISSUE THREAD

**Issue by carepack** [jaagr/polybar#1019] opened 2018-02-12 16:20 UTC
hi,

I'm trying to build my config file and I always get the message above during launch of poly bar.
The configs I tried

config for debugging:
https://pastebin.com/kf0uw2t2

full config from a user on reddit
https://pastebin.com/mNXVtiTJ

I always get this as output on commandline:
error: Failed to parse contents (reason: Unrecognized token '�')

Any idea whats causing the parser error? I have absolutely no idea where this � is coming from...
When I remove the type type = internal/i3 the strange question mark symbol is gone but states that the type = internal/i3 is missing of course
thx

**Comment by NBonaparte** [comment] 2018-02-12 17:57
What are your workspaces named in i3? I have a feeling that it might have caused this issue.

**Comment by carepack** [comment] 2018-02-12 18:06
Hi, thx for the reply:
my workspaces named:

`set $ws1  "1:  "
set $ws2  "2:  "
set $ws3  "3:  "
set $ws4  "4:  "
set $ws5  "5:  "
set $ws6  "6:  "
set $ws7  "7:  "
set $ws8  "8:  "
set $ws9  "9:  "
set $ws10 "10: " 
set $ws11 "11:  "
set $ws12 "12:  "
set $ws13 "13:  "
set $ws14 "14:  "
set $ws15 "15: "
set $ws16 "16: "
set $ws17 "17: "
set $ws18 "18: "
set $ws19 "19: "
set $ws20 "20: "`

in this way. I use symbols from ttf-awesome. the strange thing is, I have one config semi-working and I don't know why. With the semi-working  config I see the workspaces and until 1 symbol everything is shown but I can't make any changes to that file. In the moment when I insert for example
enable-click = false
no error is generated. But in the moment when I change that line to
enable-click = true
I get the same error like said above

**Comment by NBonaparte** [comment] 2018-02-12 18:19
I think the colons in the workspace names are throwing the parser off; if you remove them, does the bar still give the same error?

**Comment by carepack** [comment] 2018-02-12 18:31
you're feelin was totally right. the colons caused the error. bug?

**Comment by patrick96** [comment] 2018-02-12 21:02
Duplicate of #984

**Closed by patrick96** 2018-02-12 21:02 UTC
