### ISSUE TITLE
Module [internal/date] alternate format

### ISSUE THREAD

**Issue by nathanchere** [jaagr/polybar#1385] opened 2018-08-17 05:40 UTC
If I have two separate date modules, e.g.:

```
[module/date]
type = internal/date
label = %{F#666} %{F-}%date%
date = %a %Y-%m-%d (wk%V)
interval = 60
date-alt = %a, %d %B %Y

[module/clock]
type = internal/date
label = %{F#666} %{F-}%time%
time = %H:%M.%S
interval = 1
time-alt = %H:%M
```
then clicking `module/clock` will toggle the alternate display format for `module/date` instead of for itself. Adding more seems to have a similar effect. Only the first instance of `internal/date` has its display format alternated instead of the specific one which is actually clicked.

**Comment by nathanchere** [comment] 2018-08-17 06:09
Further on this, if I don't specify an `{field}-alt` value for a given module, clicking it doesn't affect the first module. I'm guessing it's because a click event is only bound when alt values are specified. So that binding step needs to identify which module was clicked rather than assuming the first `internal/date` module it finds is the one. I'll dig through the code and see if I can verify.

**Comment by patrick96** [comment] 2018-08-17 10:27
This is a duplicate of #1172 and #1384. You are correct, right now the internal events that are fired in no way identify from which module of the same type it came from, they all use the same event id.

The solution we may go with, but haven't yet implemented because it's quite an invasive change is to additionally use the module name in the event id.

**Closed by patrick96** 2018-08-17 10:27 UTC
Labels: duplicate
