### ISSUE TITLE
Polybar freezes i3wm when changing workspaces too fast

### ISSUE THREAD

**Issue by Dexger** [jaagr/polybar#1210] opened 2018-05-04 11:38 UTC
This is kind of a bizarre issue that does not affect normal use. If I hold down my i3 mod key (alt) and press numbers to change workspaces as fast as I can, after about 5 seconds everything will freeze except for the mouse. The computer isn't frozen though, and I can kill polybar from a tty, which returns everything to normal. Interestingly, the freeze does not happen if I have the i3 module disabled or there is a window open on each workspace. I am running polybar 3.1.0, which I installed from the Void Linux repository.

**Comment by unai-ndz** [comment] 2018-05-04 13:58
Probably a duplicate of #435

**Comment by Dexger** [comment] 2018-05-04 20:12
the behavior is different. The freezing is not dependant on what's open, but the speed at which I switch workspaces

**Comment by patrick96** [comment] 2018-05-05 08:08
@Dexger in #435 what's in the workspace is also not relevant, having certain windows open will make the freeze occur faster than others, but it also happens when the two workspaces are empty.

This is being worked on

**Closed by patrick96** 2018-05-05 08:08 UTC
Labels: duplicate
