### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by PhdTrollSlayer** [jaagr/polybar#606] opened 2017-06-04 06:27 UTC
Running Arch both the stable and -git version return this...

```
Scanning dependencies of target i3ipc++
[  2%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
In file included from /home/rodrigo/Git/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/rodrigo/Git/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:147:57: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>   i3_recv(const int32_t  sockfd) throw (invalid_header_error, eof_error);
                                                         ^~~~~
In file included from /home/rodrigo/Git/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/rodrigo/Git/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:163:131: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 ClientMessageType  type, const std::string&  payload = std::string()) throw (invalid_header_error, eof_error);
                                                                       ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [lib/i3ipcpp/CMakeFiles/i3ipc++.dir/build.make:63: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:458: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
** Failed to build project

```

**Comment by Kalagon** [comment] 2017-06-04 14:55
Polybar is currently incompatible with GCC 7.1.1. The workaround for now is to use clang. See #605 for this

**Comment by PhdTrollSlayer** [comment] 2017-06-04 18:32
Ok looks like it managed to build. Tanks @Kalagon and @Dupond

**Comment by jaagr** [comment] 2017-06-07 15:54
For you who are installing `polybar` using the AUR; I have updated the `PKGBUILD` so that `clang` will be used until the gcc issues have been fixed.

**Comment by jaagr** [comment] 2017-06-07 15:56
Closing as a duplicate of #572

**Closed by jaagr** 2017-06-07 15:56 UTC
