### ISSUE TITLE
Tray icon on top of borderless windowed game

### ISSUE THREAD

**Issue by leewdch** [jaagr/polybar#1199] opened 2018-04-30 00:26 UTC
Anyway I can solve this? When I launch the game I have the whole bar on top of it, if I switch desktop and go back to the game it's gone but the tray area stays. I'm using openbox

edit: it happens in fullscreen mode as well

polybar 3.1.0-git

```
[bar/obox]
monitor = HDMI-0
bottom = true
fixed-center = true
width = 100%
height = 40
offset-x = 0
offset-y = 0
background = ${var.background}
foreground = ${var.foreground}
radius = 0.0
line-size = 0
border-size = 0
border-color = ${var.border}
padding = 2
module-margin-right = 2
font-0 = DejavuSansMono:size=10;4
font-1 = NotoSansCJKJP:size=10;4
font-2 = FontAwesome:size=10;4
modules-left = ewmh nyaa mpd
modules-center = 
modules-right = keyboard volume date
dim-value = 1.0
override-redirect = false
tray-position = right
tray-maxsize = 16
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 1
tray-scale = 1.0
tray-background = ${var.background-light}
```

![image](https://user-images.githubusercontent.com/11262717/39412495-6d983d32-4c1d-11e8-82a1-112488b7c35f.png)

**Comment by patrick96** [comment] 2018-05-01 11:58
Seems like a lot of people have that issue. It has already been reported in #425. Can you try out the PR #1203 and check if polybar now prints any errors when you go to fullscreen.

Please report your findings over at #425 (also post the full polybar output).

There is no fix for this right now (except for switching window managers)

I am going to close this, the issue is going to be handled over at #425.

**Closed** 2018-05-01 11:58 UTC
Labels: duplicate
