### ISSUE TITLE
No rounded corners on tray

### ISSUE THREAD

**Issue by ant-i-c-s** [jaagr/polybar#1458] opened 2018-10-05 13:40 UTC
## Describe the issue

**Expected behavior:**
There are rounded corners if there is a tray

**Actual behavior:**
There are no rounded corners if there is a tray

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/test]
width = 100%
height = 30
radius = 15
modules-center = title
tray-position = right
monitor = eDP1
background = #FFFFFF
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
warn: No fonts specified, using fallback font "fixed"
error: tray: Failed to put tray above 0x1e00001 in the stack (XCB_MATCH (8))
warn: Termination signal received, shutting down...
```

## Screenshots
<a href="https://imgur.com/GxVGK1A"><img src="https://i.imgur.com/GxVGK1A.png" title="source: imgur.com" /></a>

## Environment:
* WM: i3
* Output of `polybar -vvv`:
```
polybar 3.2.0-49-g13b0ee74

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment] 2018-10-05 13:45
Duplicate of #651 

This won't happen with the new tray, but the release of that feature is still TBD

**Closed by patrick96** 2018-10-05 13:45 UTC
