### ISSUE TITLE
qt5 icons missing from tray after restart

### ISSUE THREAD

**Issue by 1earch** [jaagr/polybar#1609] opened 2019-01-16 10:18 UTC
## Describe the issue
I restart polybar every time I change my xrandr configuration (when adding a new screen for example). However, when performing this restart, the polybar system tray loses some icons: Nextcloud client, Synergy, KeepassXC. Some other programs don't disappear: nm-applet, Signal desktop, Slack

I read #828, but I'm already using the `while pgrep -u $UID -x polybar ...` to wait for all polybar processes to finish before launching new instances.

**Expected behavior:**
Show all tray icons of launched programs

**Actual behavior:**
Some icons are missing

## Environment:
* WM: i3
* Output of `polybar -vvv`:
```
polybar 3.3.0-12-g46b8bb84

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment] 2019-01-16 17:42
Hmm, all the icons that disappear are qt5 icons, we have long suspected that those don't work properly with our tray.

I was able to reproduce this and with some debugging I found that if you start polybar while the QT icon (in my case nextclound) is already running, the application doesn't register itself to polybar. It only registers itself when you start the application after polybar. So I don't think this is a bug on the polybar side but rather on the side of the application because it likely assumes that the system tray is continuously running and not getting restarted.

**Comment by asegarra** [comment] 2019-01-19 07:20
This also happens with mate-power-manager a gtk app. Starting the app after the panel makes it stick around but tint2 is not affected by this at all, it displays the tray icon no matter what order the apps are executed, tint2 must be looking for tray items upon startup in a way that polybar is not.

**Comment by patrick96** [comment] 2019-01-19 20:46
@asegarra I was not able to reproduce this. On my machine the icon always shows up. Can you make sure that you have configured the power manager to always display icons in `mate-power-preferences`:
![2019-01-19-214458_600x376_scrot](https://user-images.githubusercontent.com/2452038/51432174-9af26f00-1c33-11e9-9ee4-f1c073f185bd.png)

You may also be suffering from the issue described in #1355.

**Comment by asegarra** [comment] 2019-01-19 21:54
have only display when battery is present, so same effect but can't replicate now, it could be I had some hidden bar that took control of the systray when I was testing. thanks for looking into it.

**Comment by patrick96** [comment] 2019-01-20 14:35
@asegarra I had the issue that when switching tray implementations (between polybar, stalonetray and tint2), sometimes icons wouldn't reappear (even gtk ones). Maybe you experienced this. If it happens again during normal operation with a gtk icon, let us know.

I'll close this for now as the issue itself is not really polybar related.

**Closed by patrick96** 2019-01-20 14:35 UTC
Labels: confirmed, tray

**Comment by languitar** [comment] 2019-02-18 13:47
I'm seeing a similar behavior right now. For instance, seafile-applet disappears, nm-applet too.

**Comment by patrick96** [comment] 2019-02-20 14:27
@languitar do they also disappear after a tray restart? seafule-applet had a report that its icon disappeared sometimes (https://github.com/haiwen/seafile-client/issues/797) and also it's a QT application so this is expected. nm-applet is a gtk application, this is more concerning.

**Comment by languitar** [comment] 2019-02-20 19:22
they are basically only there until i restart the bar. immediately with the first restart of polybar (which I do when the laptop docks / undocks) the icons disappear and never come back.

**Comment by patrick96** [comment] 2019-02-20 19:47
Unfortunately I cannot test with nm-applet myself because I'm using connman. Can anyone else confirm that this is happening for them too? @languitar And this always happens?

**Comment by languitar** [comment] 2019-02-20 20:00
Hm, looks like this doesn't happen all the time for nm-applet, but for seafile it is permanent, but probably due to the seafile bug.

**Comment by aiguofer** [comment] 2019-07-03 16:57
I was running into the same issue. My work-around is to use systemd. I have polybar and all my "startup" processes running as systemd services. Then I bind apps that lose their trays to polybar, so that when it restarts they restart. For example:

rescuetime.service
``` 
[Unit]
Description=Rescuetime
After=started.target polybar.service
PartOf=graphical-session.target polybar.service

[Service]
ExecStart=/usr/bin/rescuetime
Restart=on-failure
RestartSec=2

[Install]
WantedBy=started.target
```

polybar.service
```
[Unit]
Description=Launch polybar
After=compton.service
PartOf=i3.target

[Service]
ExecStart=/usr/local/bin/polybar -l error example
Restart=always
RestartSec=2

[Install]
WantedBy=i3.target
```

Hope this is useful to someone else here!
